import {createPacer,setSpeed,advance,progress} from './realtime.js';
import {mapSVG,updateTimetable,crewHTML,depotHTML,morningHTML,preserveHTML,focusTrain} from './display.js';
import {createState,start,tick,act,preview,stations,clock,serialize,restore,result,playerInfo,connections,commandFields,completionCounts} from './engine.js';
import {evaluate,overtimeRecord} from './labor.js';
let s=createState(),speed=0,last=performance.now();const pacer=createPacer(),$=id=>document.getElementById(id);
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('trainSelect').innerHTML=s.trains.map(t=>`<option>${t.id}</option>`).join('');
$('dest').innerHTML=stations.map((n,i)=>`<option value="${i}">${n}</option>`).join('');$('dest').value='2';
$('crewSelect').innerHTML='<option value="">現地自動選定</option>'+s.crews.map(c=>`<option>${c.id}</option>`).join('');
function args(){const fields=commandFields($('actionSelect').value);return Object.fromEntries(Object.entries({service:$('serviceSelect').value||undefined,dest:Number($('dest').value),mode:$('mode').value,crew:$('crewSelect').value}).filter(([key])=>fields[key]));}
function render(){
 $('clock').textContent=clock(s.time);$('phase').textContent=s.started?s.phase:'指令待機';$('speedNote').textContent=speed?`${speed}倍 / 実1秒＝ゲーム${speed}秒 / 次tickまでゲーム${Math.ceil(60*(1-progress(pacer)))}秒`:'停止中 / 計画可能';$('notice').textContent=s.notice;
 const pending=s.important.some(n=>!n.acknowledged);$('ack').hidden=!pending;$('speedLock').textContent=pending?'重要通知の確認待ち：確認後、進行速度を選び直してください。':'';$('start').disabled=s.started;$('step').disabled=!s.started||s.ended||pending;$('scenario').disabled=s.started;document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===speed));
 const info=playerInfo(s);$('closure').textContent=info.constraint;$('important').textContent=info.latest;
 const map=$('map'),scroll=map.scrollLeft,vertical=map.scrollTop;map.innerHTML=mapSVG(s);map.scrollLeft=scroll;map.scrollTop=vertical;map.querySelectorAll('[data-train]').forEach(g=>{const pick=()=>{s.selected=g.dataset.train;render();};g.onclick=pick;g.onkeydown=e=>{if(e.key==='Enter')pick();};});
 const t=s.trains.find(t=>t.id===s.selected);$('trainSelect').value=t.id;$('selected').textContent=t.id;
 const chosen=$('serviceSelect').value;const rows=s.timetable.filter(r=>!['完了','短縮完了','運休'].includes(s.actual.find(a=>a.id===r.id).status));$('serviceSelect').innerHTML=rows.map(r=>`<option value="${r.id}">${r.id} ${clock(r.departure)} ${stations[r.origin]}→${stations[r.dest]}</option>`).join('');if(rows.some(r=>r.id===chosen))$('serviceSelect').value=chosen;else $('serviceSelect').value=rows.find(r=>s.plans.find(p=>p.id===r.id).train===t.id)?.id||rows[0]?.id||'';
 s.selectedService=$('serviceSelect').value;s.selectedCrew=$('crewSelect').value;
 $('trainInfo').textContent=`${t.id} / ${t.formation} / ${t.crew||'担当未割当'}：${t.depotTrack?'森ヶ丘車庫 留置'+t.depotTrack+'線':t.depotMove?'車庫移動あと'+t.depotMove.remaining+'分':t.edge?stations[t.edge[0]]+'→'+stations[t.edge[1]]+' あと'+t.remaining+'分 / 到着予約'+t.reserved+'番':stations[t.at]+t.platform+'番'}、${t.dir===1?'東':'西'}向き / 準備${t.busy}分 / ${t.service||'次便待機'}。所定便は自動発車。入力中も進行します。`;
 const actions=[['prepare','車庫で車両準備（5分）'],['depotOut','車庫から出庫（3分）'],['depotIn','車庫へ入庫（3分）'],['hold','便を抑止'],['resume','抑止解除'],['shorten','便の行先を短縮'],['assign','選択編成で代走・交代計画'],['reassignCycle','この便以後の運用を代走編成へ'],['restorePlan','変更を所定へ戻す'],['cancel','便を部分運休'],['dispatch','臨時運行・配置移動'],['turn','番線で反転準備'],['relief','駅抑止中の乗務交代'],['transfer','指定乗員を便乗'],['alight','便乗者を現駅で下車'],['break','指定乗員を自由休憩'],['endBreak','自由休憩を中断'],['retire','指定乗員を終業']];
 if(!$('actionSelect').innerHTML){$('actionSelect').innerHTML=actions.map(([a,label])=>`<option value="${a}">${label}</option>`).join('');$('actionSelect').value='shorten';}
 const [a,label]=actions.find(([a])=>a===$('actionSelect').value)||actions[0],p=preview(s,t.id,a,args());
 for(const [key,id] of Object.entries({service:'serviceSelect',dest:'dest',mode:'mode',crew:'crewSelect'})){$(id).disabled=!commandFields(a)[key];$(id).closest('label').hidden=!commandFields(a)[key];}
 $('actionExecute').innerHTML=`<button data-action="${a}" ${p.reason?'disabled':''}>${label}を実行</button>`; $('actions').innerHTML=`<div class="action"><small>${esc(p.info)}${p.reason?'<span class="reason">不可：'+esc(p.reason)+'</span>':''}</small></div>`;$('actionExecute').querySelectorAll('button').forEach(b=>b.onclick=()=>{act(s,s.selected,b.dataset.action,args());render();});
 $('roster').innerHTML='<table><tr><th>編成運用</th><th>位置 / 実行状態</th></tr>'+s.trains.map(t=>`<tr data-id="${t.id}" class="pick ${t.id===s.selected?'selected':''}"><td>${t.id}/${t.formation}</td><td>${t.depotTrack?'車庫'+t.depotTrack+'線':t.depotMove?'出入庫中':t.edge?stations[t.at]+'→'+stations[t.edge[1]]:stations[t.at]+t.platform+'番'} / ${t.service||'次便待ち'}<br>${t.service?esc(s.actual.find(a=>a.id===t.service).reason)||'運行中':''}</td></tr>`).join('')+'</table>';$('roster').querySelectorAll('[data-id]').forEach(r=>r.onclick=()=>{s.selected=r.dataset.id;render();});
 preserveHTML($('crews'),crewHTML(s,evaluate,overtimeRecord));preserveHTML($('depot'),depotHTML(s));preserveHTML($('morning'),morningHTML(s));
 const links=s.started?connections(s):[];$('connections').innerHTML='<table>'+links.map(x=>`<tr><td>${x.id} ${clock(x.departure)}</td><td>${x.possible?'接続成立見込':'接続不足'}：${esc(x.reason)}</td></tr>`).join('')+'</table>';
 updateTimetable($('timetable'),s);bindRelations();const r=result(s),counts=completionCounts(s);$('metrics').textContent=`目的地到着 ${r.transported}人 / 未着${r.unfinished}人 / 待ち${r.wait}人分 / 許容超勤実績${r.overtime}分 / 復旧${s.recoveryAt?clock(s.recoveryAt):'未達'}`;$('history').innerHTML=s.history.slice().reverse().map(h=>`<div>${clock(h.time)} ${esc(h.msg)}</div>`).join('');
 if(s.ended&&!s.resultViewed){s.resultViewed=true;pause();$('resultText').innerHTML=`<h2>${s.mode==='normal'?'正常所定運行の観察終了':r.success?'所定運用の復旧を確認':'復旧条件未達'}</h2><p>15:12固定観察終了。目的地到着${r.transported}人、未着${r.unfinished}人、待ち${r.wait}人分。許容超勤${r.overtime}分。評価${r.score}。</p><p>${s.mode==='normal'?'正常観察：朝から累計完了'+counts.morningTotal+'便／08:00以降の完了'+counts.observation+'便（引継ぎ時走行中'+counts.inherited+'便を含む）。08:00以降に発車・完了'+counts.observationDeparted+'便。時刻表で所定と全実績を照合できます。復旧目標の対象外です。':''}</p><p>${s.mode==='normal'?'障害なし：復旧判定対象外／所定運行の確認結果': '所定1周期の全停車・発着と翌接続：'+(s.recoveryAt?clock(s.recoveryAt)+'に成立':'未成立')}。途中運休${s.actual.filter(a=>a.status==='運休').length}、短縮完了${s.actual.filter(a=>a.status==='短縮完了').length}便。</p><p>${esc(r.violations.join(' / '))||'確定した法令・協定／社内規程違反なし。未終了勤務は自動退勤させず、続行予測の確認が必要です。'}</p><p>短縮した客は目的地を維持し、乗換後の到着だけを輸送完了として計上します。時刻表と操作履歴を確認してください。</p>`;$('result').showModal();}
}
function bindRelations(){for(const parent of ['timetable','crews','depot','morning']){const node=$(parent);node.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{s.selected=b.dataset.pick;if(b.dataset.pickservice)$('serviceSelect').value=b.dataset.pickservice;render();$('findTrain').onclick();});node.querySelectorAll('[data-pickcrew]').forEach(b=>b.onclick=()=>{const id=b.dataset.pickcrew;if(!id)return;const c=s.crews.find(c=>c.id===id);if(c?.train||c?.ride)s.selected=c.train||c.ride;$('crewSelect').value=id;render();const d=[...$('crews').querySelectorAll('details')].find(d=>d.dataset.crew===id);if(d){d.open=true;d.scrollIntoView?.({block:'center'});}});}}
function pause(){speed=0;setSpeed(pacer,0);last=performance.now();}
$('scenario').onchange=()=>{s=createState({mode:$('scenario').value});render();};$('start').onclick=()=>{start(s);render();};$('step').onclick=()=>{pause();if(!s.important.some(n=>!n.acknowledged))tick(s);render();};
for(const id of ['dest','mode','crewSelect','serviceSelect','actionSelect'])$(id).onchange=render;
document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.speed)>0&&s.important.some(n=>!n.acknowledged)){s.notice='重要通知を確認してください。';render();return;}speed=Number(b.dataset.speed);setSpeed(pacer,speed);last=performance.now();render();});
function reset(){pause();s=createState({mode:$('scenario').value});if($('result').open)$('result').close();render();}$('reset').onclick=()=>{if(confirm('現在の運行を破棄しますか？'))reset();};$('replay').onclick=reset;
$('save').onclick=()=>{try{localStorage.setItem('aoba-save-v8',serialize(s));s.notice='完全状態を保存しました。';}catch{s.notice='保存できませんでした。';}render();};$('load').onclick=()=>{try{s=restore(localStorage.getItem('aoba-save-v8'));pause();s.resultViewed=false;$('scenario').value=s.mode;}catch(e){s.notice=e.message;}render();};
$('help').onclick=()=>{pause();$('helpDialog').showModal();render();};$('closeHelp').onclick=()=>$('helpDialog').close();$('closeIntro').onclick=()=>$('intro').close();$('closeResult').onclick=()=>$('result').close();$('ack').onclick=()=>{s.important.forEach(n=>n.acknowledged=true);render();};
$('trainSelect').onchange=()=>{s.selected=$('trainSelect').value;render();};$('findTrain').onclick=()=>{const t=s.trains.find(t=>t.id===s.selected);focusTrain($('map'),t);};
document.addEventListener('visibilitychange',()=>{pause();render();});
function frame(now){const elapsed=now-last;last=now;const moved=advance(pacer,elapsed,{active:!document.hidden&&s.started&&!s.ended&&!$('intro').open&&!$('helpDialog').open,step:()=>tick(s),eventKey:()=>s.important.length+Number(s.ended)});speed=pacer.speed;if(moved)render();else $('speedNote').textContent=speed?`${speed}倍 / 実1秒＝ゲーム${speed}秒 / 次tickまでゲーム${Math.ceil(60*(1-progress(pacer)))}秒`:'停止中 / 計画可能';requestAnimationFrame(frame);}render();$('intro').showModal();requestAnimationFrame(frame);
