import test from 'node:test';import assert from 'node:assert/strict';
import{createState,start,tick,act,check,serialize,restore,validate,morningSeed}from '../engine.js';
import{equipment,yardEquipment,yardPath,validYardRoute}from '../equipment.js';
import{trainPoint,mapSVG,timetableHTML,crewHTML}from '../display.js';import{evaluate,overtimeRecord}from '../labor.js';
const ready=()=>{const s=createState({mode:'normal'});start(s);assert.ok(act(s,'T4','prepare',{crew:'C8'}));tick(s,5);return s;};
test('車庫経路の線分・分岐器stem通過と本線経路の連続性、設備変更は可否を変える',()=>{for(const r of yardEquipment.routes)assert.ok(validYardRoute(r));const s=ready(),original=equipment[7].routes;try{equipment[7].routes=original.filter(r=>r.kind!=='arrival');assert.equal(yardPath(4,1,'depotOut'),null);assert.match(check(s,'T4','depotOut',{crew:'C8'}),/有効.*接続経路/);assert.equal(act(s,'T4','depotOut',{crew:'C8'}),false);}finally{equipment[7].routes=original;}const seg=yardEquipment.segments.shift();try{assert.equal(yardPath(4,1,'depotOut'),null);assert.equal(act(s,'T4','depotOut',{crew:'C8'}),false);}finally{yardEquipment.segments.unshift(seg);}assert.ok(act(s,'T4','depotOut',{crew:'C8'}));validate(s);});
test('車庫routeのpoint設定破損・分岐側同士の不正通過は拒否',()=>{const r=structuredClone(yardEquipment.routes[1]);r.points[0].state='reverse';assert.equal(validYardRoute(r),false);r.path=['depot:1','depot:2'];assert.equal(validYardRoute(r),false);});
test('出庫中の本線喉部可用性は鎖錠、入庫は容量・担当・3分移動を消費',()=>{const s=ready();assert.ok(act(s,'T4','depotOut',{crew:'C8'}));tick(s,6);const work=s.crews[7].todayWork;assert.ok(act(s,'T4','depotIn',{crew:'C8'}));assert.equal(s.crews[7].at,null);const q=restore(serialize(s));tick(s,3);tick(q,3);assert.deepEqual(q,s);assert.equal(s.trains[3].depotTrack,1);assert.equal(s.crews[7].todayWork,work+3);validate(s);});
test('全走行・車庫移動列車は定義した線分上に描画',()=>{const s=ready();act(s,'T4','depotOut',{crew:'C8'});for(let n=0;n<3;n++){for(const t of s.trains.filter(t=>t.edge||t.depotMove)){const [x,y]=trainPoint(t);const segments=[...equipment.flatMap(e=>e.segments),...yardEquipment.segments,...Array.from({length:7},(_,at)=>({a:[140+340*at+120,90],b:[140+340*(at+1)-120,90]}))];assert.ok(segments.some(l=>{const cross=(x-l.a[0])*(l.b[1]-l.a[1])-(y-l.a[1])*(l.b[0]-l.a[0]);return Math.abs(cross)<1e-6&&x>=Math.min(l.a[0],l.b[0])-1e-6&&x<=Math.max(l.a[0],l.b[0])+1e-6&&y>=Math.min(l.a[1],l.b[1])-1e-6&&y<=Math.max(l.a[1],l.b[1])+1e-6;}),t.id);}tick(s);}for(const seg of yardEquipment.segments)assert.ok(mapSVG(s).includes(`data-segment="${seg.id}"`));});
test('入れ子の駅表・勤務区間表と時系列順、詳細は初期全展開しない',()=>{const s=createState(),html=timetableHTML(s),crew=crewHTML(s,evaluate,overtimeRecord);assert.match(html,/<section class="family/);assert.match(html,/<td colspan="5"><details[^]*?<table class="stop-table">/);for(const text of ['所定着','所定発','変更着','変更発','実着','実発','番線'])assert.ok(html.includes(text));for(const table of html.matchAll(/<table class="stop-table">(.*?)<\/table>/g))assert.doesNotMatch(table[1],/<br>/);assert.ok(crew.includes('勤務区間の実績'));assert.ok(crew.includes('value-table'));assert.doesNotMatch(crew,/<details[^>]* open/);});
test('公開API便乗・下車・現地交代：旧担当後処理2分と遠隔拒否、保存継続',()=>{const q=createState({mode:'normal'});start(q);tick(q,30);assert.ok(act(q,'T2','transfer',{crew:'C7'}));assert.ok(act(q,'T2','dispatch',{dest:7,crew:'C6'}));const extra=q.timetable.at(-1).id;tick(q,7);assert.ok(act(q,'T2','hold',{service:extra}));tick(q,4);assert.equal(q.trains[1].at,2);assert.equal(q.crews[6].ride,'T2');assert.equal(act(q,'T2','relief',{crew:'C8'}),false);assert.ok(act(q,'T2','alight',{crew:'C7'}));const before=q.crews.find(c=>c.id===q.trains[1].crew),work=before.todayWork,breaks=before.breakMinutesActual;assert.ok(act(q,'T2','relief',{crew:'C7'}));assert.equal(before.releaseAt,43);assert.equal(before.rest,0);const saved=restore(serialize(q));tick(q,2);tick(saved,2);assert.deepEqual(saved,q);assert.equal(before.todayWork,work+2);assert.equal(before.breakMinutesActual,breaks);assert.equal(before.dutySegments.at(-1).kind,'preparation');tick(q);assert.equal(before.dutySegments.at(-1).kind,'standby');});

test('車庫移動saveの未知kind・小数remaining・経路/番線/担当破損は安全拒否',()=>{const s=ready();act(s,'T4','depotOut',{crew:'C8'});for(const change of [q=>{q.trains[3].at=0;q.formations[3].at=0},q=>q.trains[3].depotMove.platform=2,q=>q.trains[3].depotMove.kind='bogus',q=>q.trains[3].depotMove.remaining=1.5,q=>q.trains[3].depotMove.track=5,q=>q.trains[3].depotMove.platform=4,q=>q.trains[3].depotMove.crew='C999',q=>q.trains[3].depotMove.route.path=['fake'],q=>q.morning.history=[]]){const q=JSON.parse(serialize(s));change(q);assert.throws(()=>restore(JSON.stringify(q)));}assert.deepEqual(restore(serialize(s)),s);});

test('本線・車庫接続ポイントは同じ実機器のnormal/reverse設定を分離',()=>{const p=equipment[7].points.find(p=>p.id==='7:depot-junction');assert.equal(p.reverse,'depot:lead');assert.equal(equipment[7].routes[0].points.find(q=>q.id===p.id).state,'normal');assert.equal(yardPath(4,1,'depotOut').points.find(q=>q.id===p.id).state,'reverse');});

test('車庫接続ポイントreverse欠損はcombined経路を無効にし出庫拒否',()=>{const s=ready(),point=equipment[7].points.find(p=>p.id==='7:depot-junction'),original=point.reverse;try{point.reverse='fake';assert.equal(yardPath(4,1,'depotOut'),null);assert.equal(act(s,'T4','depotOut',{crew:'C8'}),false);}finally{point.reverse=original;}assert.ok(act(s,'T4','depotOut',{crew:'C8'}));});
test('車庫選択は旅客4番線と混同せず留置線・限定経路を表示',()=>{const s=createState();s.selected='T4';const html=mapSVG(s);assert.ok(html.includes('森ヶ丘車庫4留置線（旅客番線ではありません）'));assert.doesNotMatch(html,/森ヶ丘4番線：出発進路/);});

test('異なる留置編成の同時出庫は同じ西喉部を二重鎖錠せず具体理由で拒否',()=>{const s=morningSeed();start(s);tick(s,20);assert.equal(s.time,-220);assert.ok(act(s,'T1','depotOut',{crew:'C4'}));assert.equal(act(s,'T2','depotOut',{crew:'C7'}),false);assert.match(s.notice,/喉部.*鎖錠/);assert.equal(s.trains[1].depotTrack,2);assert.equal(s.trains.filter(t=>t.depotMove).length,1);});
