import test from 'node:test';import assert from 'node:assert/strict';
import {createState,start,tick,act,check,preview,serialize,restore,connections,dutyForecast} from '../engine.js';
import {evaluate,intermediateBreak,workMinute,breakMinute,overtime} from '../labor.js';
test('先行日別履歴から週・月・年・過去月を再集計、実在日と8時間所定勤務を確認',()=>{
 for(const c of createState().crews){for(const d of c.history)assert.equal(new Date(d.date).toISOString().slice(0,10),d.date);assert.deepEqual(c.weekDays,c.history.filter(d=>d.date>='2026-09-28'));assert.equal(overtime(c.weekDays).overtime,0);for(const days of [c.monthHistory,c.yearHistory])assert.equal(days.reduce((n,d)=>n+Math.max(0,d.work-480),0),0);assert.deepEqual(c.previousFiveMonths,[0,0,0,0,0]);assert.equal(c.initialSegments.filter(x=>x.work).reduce((n,x)=>n+x.end-x.start,0),c.startLedger.work);assert.equal(c.scheduledDuty.totalWork,480);}
});
test('勤務前・所定終業・後続勤務は所在地を維持、正常超勤ゼロと保存継続',()=>{let s=createState({mode:'normal'});start(s);tick(s,199);assert.ok(s.crews.slice(8).every(c=>c.todayWork===0));s=restore(serialize(s));tick(s,89);assert.ok(s.crews.slice(0,8).every(c=>c.ended&&c.todayWork===480&&c.overtimeMinutes===0));assert.equal(s.stats.overtime,0);assert.deepEqual(s.violations,[]);assert.ok(connections(s).every(x=>x.possible));});
test('361分実働の後に45分だけ休憩して退勤は拒否、休憩前後の勤務で充足',()=>{const c=structuredClone(createState().crews[0]);Object.assign(c,{todayWork:361,weekDays:[],initialSegments:[],dutySegments:[{start:0,end:361,kind:'standby',work:true}],breakMinutesActual:0});for(let m=362;m<=406;m++)breakMinute(c,m);assert.equal(intermediateBreak(c),0);assert.equal(evaluate(c,{complete:true}).allowed,false);assert.equal(evaluate(c).breakNeeded,45);for(let m=407;m<=466;m++)workMinute(c,m,'standby');assert.equal(intermediateBreak(c),45);assert.equal(evaluate(c,{complete:true}).allowed,true);});
test('174分連続乗務＋中央学園前6分走行は180ちょうど：割当・プレビュー・発車・実績一致',()=>{const s=createState({mode:'normal'});start(s);const c=s.crews[7];c.continuousDrivingMinutes=174;c.duty=174;assert.deepEqual(dutyForecast(2),{extra:9,driving:6});assert.equal(check(s,'T2','assign',{service:'B032',crew:'C8'}),'');assert.equal(preview(s,'T2','assign',{service:'B032',crew:'C8'}).reason,'');assert.equal(act(s,'T2','assign',{service:'B032',crew:'C8'}),true);tick(s,39);assert.equal(s.actual.find(a=>a.id==='B032').status,'完了');assert.equal(c.continuousDrivingMinutes,180);assert.deepEqual(s.violations,[]);});
test('181分になる未実行指令は拒否し実績と減点不変',()=>{const s=createState({mode:'normal'});start(s);s.crews[7].continuousDrivingMinutes=175;const before=JSON.stringify(s.crews);assert.equal(act(s,'T2','assign',{service:'B032',crew:'C8'}),false);assert.equal(JSON.stringify(s.crews),before);assert.deepEqual(s.violations,[]);});
test('履歴・所定勤務の改変および旧saveは拒否',()=>{const s=createState({mode:'normal'});start(s);tick(s,30);for(const change of [q=>q.crews[0].weekDays[0].work++,q=>q.crews[0].previousFiveMonths[0]++,q=>q.crews[0].scheduledDuty.totalWork++,q=>q.crews[0].initialSegments[0].end++,q=>q.version=5]){const q=JSON.parse(serialize(s));change(q);assert.throws(()=>restore(JSON.stringify(q)));}});
