import test from 'node:test';import assert from 'node:assert/strict';
import {createState,start,tick,act,check,serialize,restore,dutyForecast} from '../engine.js';
import {evaluate,intermediateBreak,workMinute,breakMinute,overtime} from '../labor.js';
test('過去日別履歴と朝の勤務区間から08:00の台帳を再集計',()=>{for(const c of createState().crews){assert.equal(overtime(c.weekDays).overtime,0);assert.deepEqual(c.previousFiveMonths,[0,0,0,0,0]);assert.equal(c.initialSegments.filter(x=>x.work).reduce((n,x)=>n+x.end-x.start,0),c.startLedger.work);assert.equal(c.initialSegments.filter(x=>!x.work).reduce((n,x)=>n+x.end-x.start,0),c.startLedger.break);assert.equal(c.dutyStart,c.scheduledDuty.start);assert.equal(c.plannedDutyEnd,c.scheduledDuty.end);const last=c.history.filter(d=>d.work>0).at(-1);assert.equal(c.previousDutyEnd,(Date.parse(last.date+'T'+last.end+':00+09:00')-Date.parse('2026-10-04T08:00:00+09:00'))/60000);assert.ok(c.dutyStart===-230||c.dutyStart===180);assert.notEqual(c.locationState,c.dutyStart<0?'beforeDuty':'standby');}});
test('所定休憩・後処理・終業・後続勤務は現地で自動、正常432分まで超勤ゼロ',()=>{let s=createState({mode:'normal'});start(s);tick(s,179);assert.ok(s.crews.filter(c=>c.dutyStart===180).every(c=>c.todayWork===0));s=restore(serialize(s));tick(s,253);for(const c of s.crews.filter(c=>c.dutyStart<0)){assert.equal(c.ended,true);assert.equal(c.todayWork,480);assert.equal(c.scheduledDuty.totalWork,480);assert.equal(c.todayWork,c.initialSegments.concat(c.dutySegments).filter(x=>x.work).reduce((n,x)=>n+x.end-x.start,0));}assert.equal(s.stats.overtime,0);assert.deepEqual(s.violations,[]);s.ended=false;s.forecast=true;s.knownPhase=s.phase;tick(s,65);assert.equal(s.stats.overtime,0);assert.deepEqual(s.violations,[]);for(const r of s.timetable.filter(r=>r.departure>=288&&r.stops.at(-1).arrival<=353))assert.equal(s.actual.find(a=>a.id===r.id).actualDeparture,r.departure);});
test('末尾45分休憩だけの退勤拒否と、実業務を挟む勤務途中休憩の判定',()=>{const c=structuredClone(createState().crews[0]);Object.assign(c,{todayWork:361,weekDays:[],initialSegments:[],dutySegments:[{start:0,end:361,kind:'standby',work:true}],breakMinutesActual:0});for(let m=362;m<=406;m++)breakMinute(c,m);assert.equal(intermediateBreak(c),0);assert.equal(evaluate(c,{complete:true}).allowed,false);for(let m=407;m<=466;m++)workMinute(c,m,'standby');assert.equal(intermediateBreak(c),45);assert.equal(evaluate(c,{complete:true}).allowed,true);});
test('174分＋実走行6分・実働9分の予測が180境界を認める',()=>{assert.deepEqual(dutyForecast(2),{extra:9,driving:6});const c=structuredClone(createState().crews[7]);c.continuousDrivingMinutes=174;assert.equal(evaluate(c,{...dutyForecast(2)}).allowed,true);assert.equal(evaluate(c,{...dutyForecast(2),driving:7}).allowed,false);});
test('予測拒否は勤務実績・超勤減点・失格を加えず、遠隔交代を拒否',()=>{const s=createState({mode:'normal'});start(s);tick(s,3);act(s,'T2','hold',{service:'B008'});tick(s,5);const before=JSON.stringify(s.crews);assert.equal(act(s,'T2','relief',{crew:'C8'}),false);assert.equal(JSON.stringify(s.crews),before);assert.deepEqual(s.violations,[]);});
test('先行履歴・朝勤務・所定勤務・旧saveの改変は拒否',()=>{const s=createState();start(s);for(const change of [q=>q.crews[0].weekDays[0].work++,q=>q.crews[0].initialSegments[0].end++,q=>q.crews[0].scheduledDuty.start++,q=>q.version=7]){const q=JSON.parse(serialize(s));change(q);assert.throws(()=>restore(JSON.stringify(q)));}});
