import test from 'node:test';import assert from 'node:assert/strict';
import {createState,start,tick,act,check,serialize,restore,result,routeClosureReason} from '../engine.js';
import {guidance,crewCandidates} from '../guidance.js';
const fresh=()=>{const s=createState();start(s);return s;};
function choose(s,id,action,arg={}){const g=guidance(s,id,arg.service);const item=g.choices.find(x=>x.action===action&&Object.entries(arg).every(([k,v])=>x.arg[k]===v));assert.ok(item,`${s.time} ${id} ${action} ${JSON.stringify(arg)}`);assert.ok(act(s,id,item.action,item.arg));return item;}
test('既知閉鎖横断は候補/APIで同じ理由、実績・資源不変、合法部分運転を保持',()=>{const s=fresh();tick(s,8);choose(s,'T4','prepare');tick(s,6);choose(s,'T4','depotOut');tick(s,6);const before=serialize(s),g=guidance(s,'T4');const blocked=g.blocked.find(x=>x.action==='dispatch'&&x.arg.dest===0);assert.match(blocked.reason,/東川原―川原.*西/);assert.equal(check(s,'T4',blocked.action,blocked.arg),blocked.reason);assert.equal(act(s,'T4',blocked.action,blocked.arg),false);s.notice=JSON.parse(before).notice;assert.equal(serialize(s),before);choose(s,'T4','dispatch',{dest:4});assert.equal(act(s,'T4','dispatch',{dest:4}),false);});
test('方向別閉鎖・再開は未確定時刻を使わず変化、安全退出は維持',()=>{const s=fresh();tick(s,5);assert.ok(routeClosureReason(s,0,7));assert.ok(routeClosureReason(s,7,0));const prior=s.trains.filter(t=>t.edge);tick(s,3);assert.ok(prior.every(t=>!t.edge||t.edge[0]!==3));tick(s,12);assert.equal(routeClosureReason(s,0,7),'');assert.ok(routeClosureReason(s,7,0));tick(s,45);assert.equal(routeClosureReason(s,7,0),'');assert.deepEqual(s.violations,[]);});
test('将来計画を閉鎖中に保存復元し条件未成立で新規進入しない',()=>{let s=fresh();tick(s,5);choose(s,'T1','planResume',{service:'AM012'});s=restore(serialize(s));tick(s,10);assert.equal(s.plans.find(p=>p.id==='AM012').waitForRoute,true);assert.ok(!s.trains.some(t=>t.edge&&Math.min(...t.edge)===3));});
test('候補担当者は現地・勤務・資格・休憩条件を共通checkで満たす',()=>{const s=fresh();tick(s,8);let cs=crewCandidates(s,'T4','prepare');assert.ok(cs.length);const c=s.crews.find(c=>c.id===cs[0].id);for(const change of [{rest:20},{at:0},{qualifications:[]},{fitForDuty:false},{ended:true}]){const original=structuredClone(c);Object.assign(c,change);assert.ok(!crewCandidates(s,'T4','prepare').some(x=>x.id===c.id));Object.assign(c,original);}});
test('通常候補の判断だけで待機救援方針と部分運転方針を固定観察まで進める',()=>{for(const policy of ['waiting','partial']){const s=fresh();while(!s.ended){if(s.time===5&&policy==='waiting'){choose(s,'T1','planResume',{service:'AM012'});choose(s,'T3','planResume',{service:'DM008'});}if(s.time===5&&policy==='partial'){choose(s,'T1','resume',{service:'AM012'});choose(s,'T3','resume',{service:'DM008'});choose(s,'T1','shorten',{service:'A024',dest:4});choose(s,'T3','shorten',{service:'D028',dest:2});}tick(s);}console.log('通常候補完走',policy,JSON.stringify(result(s)));assert.equal(s.time,432);}});

import {strategy} from './strategies.mjs';
test('通常候補と適格者比較から部分運転・予備救援の2戦略が復旧成功',()=>{for(const policy of ['local','wait-rescue']){const s=strategy(policy,()=>{},true);assert.ok(result(s).success);console.log('通常導線復旧',policy,JSON.stringify(result(s)),s.recoveryAt);}});
