import test from 'node:test';
import assert from 'node:assert/strict';
import {createState,serialize,restore,result,start,tick,preview} from '../engine.js';
import {evaluate,workMinute,overtimeRecord} from '../labor.js';
import {strategy} from './strategies.mjs';
function crew(work=480,end=100){const c=structuredClone(createState().crews[0]);Object.assign(c,{todayWork:work,weekDays:[],plannedDutyEnd:end,dutySegments:[],overtimeMinutes:0});c.startLedger.work=work;return c;}
test('終業前の法定時間外、終業超過のみ、両方の同一分は一度採点し予測と一致',()=>{for(const [work,end,expected] of [[480,100,1],[400,0,1],[480,0,1],[479,100,0]]){const c=crew(work,end);const e=evaluate(c,{extra:1,now:0});assert.equal(e.additionalOvertime,expected);workMinute(c,1,'standby');assert.equal(c.overtimeMinutes,expected);assert.equal(overtimeRecord(c).charged,expected);}});
test('週追加時間外を採点し日超勤と二重計上しない',()=>{const c=crew(420);c.weekDays=Array(5).fill({work:420,holiday:false});workMinute(c,1,'preparation');assert.equal(c.overtimeMinutes,1);assert.equal(c.monthOvertime,1);const d=crew(480);d.weekDays=Array(4).fill({work:540,holiday:false});workMinute(d,1,'standby');assert.equal(d.overtimeMinutes,1);});
test('先行時間外は減点せず新規分のみ、予測自体は台帳を変更しない',()=>{const c=crew(510);c.monthOvertime=30;c.yearOvertime=30;c.startLedger.month=30;c.startLedger.year=30;const before=JSON.stringify(c);assert.equal(evaluate(c,{extra:2,now:0}).additionalOvertime,2);assert.equal(JSON.stringify(c),before);assert.equal(c.overtimeMinutes,0);workMinute(c,1,'riding');assert.equal(c.overtimeMinutes,1);assert.equal(c.monthOvertime,31);assert.equal(overtimeRecord(c).charged,1);});
test('多分予測は法定と所定の重複を除外、初期残量を採点しない',()=>{const c=crew(478,2);assert.equal(evaluate(c,{extra:5,now:0}).additionalOvertime,3);for(let m=1;m<=5;m++)workMinute(c,m,'preparation');assert.equal(c.overtimeMinutes,3);});
test('新配置の全戦略の採点・保存往復と改変拒否が一致',()=>{for(const policy of ['local','wait-rescue','wait-only']){const s=strategy(policy);const n=s.crews.reduce((n,c)=>n+overtimeRecord(c).charged,0);assert.equal(result(s).overtime,n);assert.equal(restore(serialize(s)).stats.overtime,n);const q=JSON.parse(serialize(s));q.crews[0].overtimeMinutes++;q.stats.overtime++;assert.throws(()=>restore(JSON.stringify(q)));}});
test('勤務延長予告は実担当を使い所定終業と法定時間外を重複除外する',()=>{const s=createState();start(s);const c=s.crews.find(c=>c.id===s.trains[0].crew);const p=preview(s,'T1','hold',{service:'AM012',crew:'C8'});assert.ok(p.info.includes('候補 '+c.id+'：'));assert.ok(!p.info.includes('候補 C8：'));});
