import test from 'node:test';
import assert from 'node:assert/strict';
import {createState,serialize,restore,result,start,tick,preview} from '../engine.js';
import {evaluate,workMinute,overtimeRecord} from '../labor.js';
import {strategy} from './strategies.mjs';
function crew(work=480,end=100){const c=structuredClone(createState().crews[0]);Object.assign(c,{todayWork:work,weekDays:[],plannedDutyEnd:end,dutySegments:[],overtimeMinutes:0});c.startLedger.work=work;return c;}
test('終業前の法定時間外、終業超過のみ、両方の同一分は一度採点し予測と一致',()=>{for(const [work,end,expected] of [[480,100,1],[400,0,1],[480,0,1],[479,100,0]]){const c=crew(work,end);const e=evaluate(c,{extra:1,now:0});assert.equal(e.additionalOvertime,expected);workMinute(c,1,'standby');assert.equal(c.overtimeMinutes,expected);assert.equal(overtimeRecord(c).charged,expected);}});
test('週追加時間外を採点し日超勤と二重計上しない',()=>{const c=crew(420);c.weekDays=Array(5).fill({work:420,holiday:false});workMinute(c,1,'preparation');assert.equal(c.overtimeMinutes,1);assert.equal(c.monthOvertime,1);const d=crew(480);d.weekDays=Array(4).fill({work:540,holiday:false});workMinute(d,1,'standby');assert.equal(d.overtimeMinutes,1);});
test('先行時間外は減点せず新規分のみ、予測自体は台帳を変更しない',()=>{const c=crew(510);c.monthOvertime=30;c.yearOvertime=30;c.startLedger.month=30;c.startLedger.year=30;const before=JSON.stringify(c);assert.equal(evaluate(c,{extra:2,now:0}).additionalOvertime,2);assert.equal(JSON.stringify(c),before);assert.equal(c.overtimeMinutes,0);workMinute(c,1,'riding');assert.equal(c.overtimeMinutes,1);assert.equal(c.monthOvertime,31);assert.equal(overtimeRecord(c).charged,1);});
test('多分予測は法定と所定の重複を除外、初期残量を採点しない',()=>{const c=crew(478,2);assert.equal(evaluate(c,{extra:5,now:0}).additionalOvertime,3);for(let m=1;m<=5;m++)workMinute(c,m,'preparation');assert.equal(c.overtimeMinutes,3);});
test('戦略の法定時間外を採点、保存往復・改変拒否・結果一致',()=>{for(const policy of ['local','wait-rescue','wait-only']){const s=strategy(policy);const n=s.crews.reduce((n,c)=>n+overtimeRecord(c).charged,0);assert.equal(result(s).overtime,n);assert.equal(n,({local:30,'wait-rescue':12,'wait-only':0})[policy]);assert.equal(restore(serialize(s)).stats.overtime,n);const q=JSON.parse(serialize(s));q.crews[0].overtimeMinutes++;q.stats.overtime++;assert.throws(()=>restore(JSON.stringify(q)));if(policy==='local'){assert.equal(s.crews[0].todayWork,510);assert.equal(s.crews[0].overtimeMinutes,30);}}});

test('便短縮の超勤予告は残った入力の別人でなく実担当、割当は変更計画の距離',()=>{const s=createState();start(s);tick(s,5);const c=s.crews.find(c=>c.id===s.trains[0].crew);const a=preview(s,'T1','shorten',{service:'A000',dest:2,crew:'C8'});assert.ok(a.info.includes('候補 '+c.id+'：'));assert.ok(!a.info.includes('候補 C8：'));const q=createState({mode:'normal'});start(q);q.crews[7].todayWork=480;const b=preview(q,'T2','assign',{service:'B032',crew:'C8',dest:7});assert.ok(b.info.includes('追加評価対象超勤見込41分'));});
