import test from 'node:test';import assert from 'node:assert/strict';
import {createPacer,setSpeed,advance,progress} from '../realtime.js';
import {createState,start,tick,act,playerInfo,serialize,restore} from '../engine.js';
import {mapSVG} from '../display.js';import {readFileSync} from 'node:fs';
function setup(speed){const s=createState();start(s);const p=createPacer();setSpeed(p,speed);const context={step:()=>tick(s),eventKey:()=>s.important.length+Number(s.ended)};return {s,p,context};}
test('1倍の1秒は1分を進めず60秒で1分、60倍との実時間関係',()=>{const {s,p,context}=setup(1);advance(p,1000,context);assert.equal(s.time,0);assert.equal(progress(p),1/60);for(let i=1;i<60;i++)advance(p,1000,context);assert.equal(s.time,1);const fast=setup(60);advance(fast.p,1000,fast.context);assert.equal(fast.s.time,1);});
test('停止再開・非表示・長いフレームからの復帰でcatch-upしない',()=>{const {s,p,context}=setup(1);advance(p,1000,context);setSpeed(p,0);advance(p,1000,context);setSpeed(p,60);advance(p,100000,context);assert.equal(s.time,0);advance(p,1000,{...context,active:false});assert.equal(s.time,0);advance(p,1000,context);assert.equal(s.time,1);});
test('複数tick高速更新は各重大境界で停止し余剰を破棄、確認で再開しない',()=>{const {s,p,context}=setup(240);for(const boundary of [5,20,65]){setSpeed(p,240);while(p.speed)advance(p,2000,context);assert.equal(s.time,boundary);assert.equal(p.elapsed,0);assert.equal(p.speed,0);s.important.forEach(n=>n.acknowledged=true);advance(p,1000,context);assert.equal(s.time,boundary);}});
test('各段階projectionと図は未発生の事故情報を含まず、操作で重大通知を消さない',()=>{const {s}=setup(1);for(const time of [0,5,20,65]){tick(s,time-s.time);const view=JSON.stringify(playerInfo(s))+mapSVG(s);for(const future of [5,20,65].filter(t=>t>time)){assert.ok(!view.includes({5:'08:05',20:'08:20',65:'09:05'}[future]));}if(time===0)assert.ok(!JSON.stringify(playerInfo(s)).includes('川原'));if(time===20)assert.ok(!view.includes('09:05'));const before=playerInfo(s);act(s,'T1','hold');assert.deepEqual(playerInfo(s),before);assert.deepEqual(restore(serialize(s)),s);}});
test('通常説明と開始DOMは故障の時刻・区間を予告しない',()=>{const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');const readme=readFileSync(new URL('../README.md',import.meta.url),'utf8').split('<details><summary>ネタバレ')[0];for(const text of [html,readme])for(const forbidden of ['08:05','08:20','09:05','故障予告','設備復旧予定'])assert.ok(!text.includes(forbidden),forbidden);});
