import {createPacer,setSpeed,advance,progress} from './realtime.js';
import {mapSVG,updateTimetable} from './display.js';
import {createState,start,tick,act,preview,stations,hubs,clock,serialize,restore,result,playerInfo,closed,departureReason} from './engine.js';
let s=createState(),speed=0,last=performance.now();const pacer=createPacer();const $=id=>document.getElementById(id);const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('dest').innerHTML=stations.map((n,i)=>`<option value="${i}">${n}</option>`).join('');$('dest').value='2';
function arrivalEstimate(s,t){const d=Math.sign(t.dest-t.at);for(let a=t.edge?t.edge[1]:t.at;a!==t.dest;a+=d)if(closed(s,a,a+d))return '未定（閉鎖待ち）';if(!t.edge&&departureReason(s,t))return '未定（進路・番線待ち）';return clock(s.time+(t.edge?t.remaining+Math.abs(t.dest-t.edge[1])*4:Math.abs(t.dest-t.at)*4)+t.busy)+'頃';}
function render(){
 $('clock').textContent=clock(s.time);$('phase').textContent=s.started?s.phase:'指令待機';$('speedNote').textContent=speed?`${speed}倍 / 実1秒＝ゲーム${speed}秒 / 次の1分まで${Math.ceil(60*(1-progress(pacer)))}秒（ゲーム時間）`:'停止中 / 計画可能';$('notice').textContent=s.notice;$('start').disabled=s.started;$('step').disabled=!s.started||s.ended||s.important.some(n=>!n.acknowledged);document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===speed));
 const info=playerInfo(s);$('closure').textContent=info.constraint;$('important').textContent=info.latest;$('ack').hidden=!s.important.some(n=>!n.acknowledged);
 $('map').innerHTML=mapSVG(s);updateTimetable($('timetable'),s);$('map').querySelectorAll('[data-train]').forEach(g=>{const pick=()=>{s.selected=g.dataset.train;render();};g.onclick=pick;g.onkeydown=e=>{if(e.key==='Enter')pick();};});
 const t=s.trains.find(t=>t.id===s.selected),c=s.crews.find(c=>c.id===t.crew);$('selected').textContent=t.id;$('trainSelect').value=t.id;
 $('trainInfo').innerHTML=`編成 ${t.formation} / ${t.crew||'乗務員未割当'}<br>${t.edge?`${stations[t.edge[0]]}→${stations[t.edge[1]]} あと${t.remaining}分 / 到着予約${t.reserved}番線`:stations[t.at]+t.platform+'番線'} / ${t.dir===1?'東向き':'西向き'} / 準備${t.busy}分<br>乗務 ${c?c.duty:'—'}/36分 / ${t.dest===null?'運用未指定':`${t.mode} ${stations[t.dest]}行`} / 自動${t.auto?'ON':'OFF'}<br>同乗：${t.riders.join('・')||'なし'}`;
 const actions=[['dispatch','発車・運用指定'],['hold','抑止'],['turn','折り返し'],['rest','8分休憩'],['relief','交代・予備投入'],['transfer','待機乗務員同乗'],['alight','同乗乗務員降車'],['auto',t.auto?'自動折返し OFF':'自動折返し ON']];const arg={dest:Number($('dest').value),mode:$('mode').value};
 $('actions').innerHTML=actions.map(([key,label])=>{let p=preview(s,t.id,key,arg);return `<div class="action"><button data-action="${key}" ${p.reason?'disabled':''}>${label}</button><small>${esc(p.info)}${p.reason?`<span class="reason">不可：${esc(p.reason)}</span>`:''}</small></div>`;}).join('');$('actions').querySelectorAll('button').forEach(b=>b.onclick=()=>{act(s,s.selected,b.dataset.action,{dest:Number($('dest').value),mode:$('mode').value});render();});
 $('roster').innerHTML='<table><tr><th>列車/編成</th><th>位置・番線</th><th>行先 / 到着見込</th></tr>'+s.trains.map(t=>`<tr class="pick ${t.id===s.selected?'selected':''}" data-id="${t.id}"><td>${t.id} / ${t.formation}</td><td>${t.edge?stations[t.edge[0]]+'→'+stations[t.edge[1]]:stations[t.at]+' '+t.platform+'番'}<br>${t.busy?'準備'+t.busy+'分':t.edge?'走行中':'停車'}</td><td>${t.dest===null?'—':stations[t.dest]+'<br>'+arrivalEstimate(s,t)}${t.auto?' / 自動':''}</td></tr>`).join('')+'</table>';$('roster').querySelectorAll('[data-id]').forEach(row=>row.onclick=()=>{s.selected=row.dataset.id;render();});
 $('crews').innerHTML='<table>'+s.crews.map(c=>`<tr><td>${c.id}</td><td>${c.train?'担当 '+c.train:c.ride?'同乗 '+c.ride:'待機'} / ${c.at===null?'走行中':stations[c.at]}</td><td>${c.duty}/36分${c.rest?' / 休憩あと'+c.rest+'分':''}</td></tr>`).join('')+'</table>';
 const r=result(s);$('metrics').innerHTML=[[r.transported,'輸送人・区間'],[r.wait,'総待ち人分'],[r.west+'/2','全線 西向き完了'],[r.east+'/2','全線 東向き完了']].map(([v,n])=>`<div class="metric"><strong>${v}</strong><span>${n}</span></div>`).join('');$('history').innerHTML=s.history.slice().reverse().map(h=>`<div>${clock(h.time)} ${esc(h.msg)}</div>`).join('');
 if(s.ended&&!$('result').open&&!s.resultViewed){speed=0;setSpeed(pacer,0);s.resultViewed=true;$('resultText').innerHTML=`<h2>${r.success?'運用復旧、達成。':'指令時間、終了。'}</h2><p>${r.success?clock(s.recoveryAt)+'に輸送と配置の復旧を達成しました。':'全線が開通しても、運用はまだ戻りませんでした。'}</p><p>輸送 ${r.transported}人・区間 / 総待ち ${r.wait}人分<br>全線 西向き${r.west}本・東向き${r.east}本 / 目標不足${s.stats.cancelled}本<br>輸送評価 ${r.score}（輸送−待ち÷100＋復旧500）</p><p>最終配置：${r.distribution.join(' / ')}</p><p>指定運用の運休 ${s.timetable.filter(r=>r.status==='運休').length}件。列車別時刻表に各運用の予定・到着実績・遅れを保存しています。</p><h3>08:35再開時の配置・乗務余裕</h3><table>${(s.reopenSnapshot||[]).map(x=>`<tr><td>${x.id}</td><td>${stations[x.at]}${x.moving?'から走行中':'停車'}</td><td>${x.crew||'未割当'} / 残り${x.duty===null?'—':36-x.duty}分</td></tr>`).join('')}</table><p>折り返し ${s.history.filter(h=>h.msg.includes('折り返し準備')).length}回、休憩 ${s.history.filter(h=>h.msg.includes('乗務員休憩')).length}回、交代 ${s.history.filter(h=>h.msg.includes('へ交代')).length}回。早い部分輸送は待ちを減らす一方、再開時の乗務余裕を消費します。下の履歴で実施時刻と最終配置を比べてください。</p><details><summary>この指令の操作履歴</summary>${s.history.map(h=>`<div>${clock(h.time)} ${esc(h.msg)}</div>`).join('')}</details>`;$('result').showModal();}
}
$('dest').onchange=render;$('mode').onchange=render;$('start').onclick=()=>{start(s);render();};$('step').onclick=()=>{speed=0;setSpeed(pacer,0);tick(s);render();};document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{if(s.important.some(n=>!n.acknowledged)&&Number(b.dataset.speed)>0){s.notice='重要通知を確認してください。上の「確認」操作で解除できます。';render();return;}speed=Number(b.dataset.speed);setSpeed(pacer,speed);last=performance.now();render();});
function reset(){speed=0;setSpeed(pacer,0);s=createState();$('dest').value='2';if($('result').open)$('result').close();render();}$('reset').onclick=()=>{if(confirm('現在の運転を破棄して08:00からやり直しますか？'))reset();};$('replay').onclick=reset;
$('save').onclick=()=>{try{localStorage.setItem('aoba-save-v1',serialize(s));s.notice='現在の完全な状態を保存しました。';}catch{s.notice='保存できません。ブラウザーの保存設定・空き容量を確認してください。';}render();};$('load').onclick=()=>{try{const raw=localStorage.getItem('aoba-save-v1');if(!raw)throw Error('保存がありません。');const loaded=restore(raw);s=loaded;speed=0;setSpeed(pacer,0);s.resultViewed=false;s.notice='保存状態を読み込みました。停止中です。';}catch(e){s.notice=e.message;}render();};
$('help').onclick=()=>$('helpDialog').showModal();$('closeHelp').onclick=()=>$('helpDialog').close();$('closeIntro').onclick=()=>$('intro').close();$('closeResult').onclick=()=>$('result').close();
$('ack').onclick=()=>{s.important.forEach(n=>n.acknowledged=true);render();};
document.addEventListener('visibilitychange',()=>{speed=0;setSpeed(pacer,0);last=performance.now();render();});
function frame(now){const elapsed=now-last;last=now;const moved=advance(pacer,elapsed,{active:!document.hidden&&s.started&&!s.ended&&!$('intro').open&&!$('helpDialog').open,step:()=>tick(s),eventKey:()=>s.important.length+Number(s.ended)});speed=pacer.speed;if(moved)render();else $('speedNote').textContent=speed?`${speed}倍 / 実1秒＝ゲーム${speed}秒 / 次tickまでゲーム${Math.ceil(60*(1-progress(pacer)))}秒`:'停止中 / 計画可能';requestAnimationFrame(frame);}render();$('intro').showModal();requestAnimationFrame(frame);
$('trainSelect').onchange=()=>{s.selected=$('trainSelect').value;render();};
