import {stations,capacities,hubs,platformUse,clock,serviceDelay,departureReason,connections} from './engine.js';
import {equipment,stationX,platformY,route,yardEquipment} from './equipment.js';
const xAt=stationX,yAt=platformY;
// 設備の存在と経路の可用性を分離。実信号現示はモデル化しない。
export function routeAvailability(s,at,platform,dir){
 const out=route(at,platform,'departure',dir);
 if(!out)return {status:'経路なし',reason:`${stations[at]}${platform}番線には${dir===1?'東':'西'}向き出発信号／列車進路がありません。`};
 const active=s.trains.filter(t=>t.edge).flatMap(t=>[t.departureRoute,t.arrivalRoute]).filter(Boolean).map(id=>equipment.flatMap(e=>e.routes).find(r=>r.id===id));
 if(s.trains.some(t=>t.depotMove?.route?.locks.some(l=>out.locks.includes(l))))return {status:'進路鎖錠中',reason:'車庫出入庫がこの喉部を使用中です。'};
 if(active.some(r=>r?.locks.some(l=>out.locks.includes(l))))return {status:'進路鎖錠中',reason:'走行列車がこの駅側の進路資源を使用中です。'};
 const occupant=s.trains.find(t=>!t.edge&&t.at===at&&t.platform===platform);
 const reason=departureReason(s,{...(occupant||{}),at,platform,dir,dest:occupant?.dest??(dir===1?7:0),auto:false},dir,at+dir);
 return {status:reason?(reason.includes('占有中')?'閉塞待ち':'設定不可'):'設定可能',reason:reason||'未設定。発車操作で経路を設定・鎖錠します（乗務員・準備条件は操作欄で確認）。'};
}
export function mapSVG(s){
 let out='<svg viewBox="0 0 2660 500" role="img" aria-label="駅間単線・方向別信号と番線。横スクロールで詳細を確認">';
 for(let i=0;i<7;i++){
 const blocked=i===3&&['区間閉鎖','片方向再開'].includes(s.phase);
 out+=`<path data-block="${i}" d="M ${xAt(i)+120} 90 H ${xAt(i+1)-120}" stroke="${blocked?'#e6a665':'#739bac'}" stroke-width="4"/><text x="${xAt(i)+170}" y="62" text-anchor="middle" fill="#edbc76" font-size="14">${blocked?s.phase==='区間閉鎖'?'閉鎖':'東 → のみ':'単線'}</text>`;
 }
 equipment.forEach(e=>{
 const x=xAt(e.at);out+=`<text x="${x}" y="22" text-anchor="middle" fill="#e1edf5" font-size="18">${e.name}</text>`;
 for(const seg of e.segments)out+=`<path data-segment="${seg.id}" d="M ${seg.a.join(' ')} L ${seg.b.join(' ')}" stroke="#739bac" stroke-width="3" fill="none"/>`;
 for(const p of e.platforms){const y=yAt(p.number);out+=`<rect x="${x-40}" y="${y+15}" width="80" height="8" fill="#8193a0"/><text x="${x+50}" y="${y+20}" fill="#dce5ed" font-size="14">${p.number}番</text>`;
 if(e.at===0||e.at===7){const end=x+(e.at===0?-48:48);out+=`<path d="M ${end} ${y-8} V ${y+8}" stroke="#dce5ed" stroke-width="5"/>`;}
 const u=platformUse(s,e.at).find(u=>u.platform===p.number);if(u?.reserved)out+=`<text x="${x}" y="${y-16}" text-anchor="middle" fill="#edbc76" font-size="14">${u.id} 到着予約</text>`;
 }
 for(const signal of e.signals){
 if(!signal.id.includes(':out:')){const side=-signal.dir;const x1=x+side*120;out+=`<g data-signal="${signal.id}"><title>${e.name} ${signal.dir===1?'東':'西'}向き場内信号設備：番線への進入経路（実現示は表示しません）</title><rect x="${x1-4}" y="59" width="8" height="12" fill="none" stroke="#aac0ce" stroke-width="2"/><text x="${x1-10}" y="48" fill="#dce5ed" font-size="14">場内${signal.dir===1?'→':'←'}</text></g>`;continue;}
 if(!route(e.at,signal.platform,'departure',signal.dir))continue;
 const x1=x+signal.dir*40,y=yAt(signal.platform)-12;
 out+=`<g data-signal="${signal.id}"><title>${e.name}${signal.platform}番 ${signal.dir===1?'東':'西'}向き出発信号設備（実現示は表示しません）</title><rect x="${x1-4}" y="${y-6}" width="8" height="12" fill="none" stroke="#aac0ce" stroke-width="2"/><text x="${x1+signal.dir*10}" y="${y+4}" fill="#dce5ed" font-size="14">${signal.dir===1?'→':'←'}</text></g>`;
 }

 out+=`<text x="${x}" y="302" text-anchor="middle" fill="#9eb3c5" font-size="14">待ち ${s.waiting[e.at]}人${e.at===7?' / 車庫：西喉部接続':''}</text>`;
 });
 for(const seg of yardEquipment.segments)out+=`<path data-segment="${seg.id}" d="M ${seg.a.join(' ')} L ${seg.b.join(' ')}" stroke="#739bac" stroke-width="3" fill="none"/>`;out+=`<text x="2520" y="310" text-anchor="middle" fill="#e1edf5" font-size="18">森ヶ丘車庫（西喉部接続）</text>`;for(const track of yardEquipment.tracks){const y=330+(track.number-1)*36;out+=`<text x="2600" y="${y+5}" fill="#dce5ed" font-size="14">留置${track.number}</text><path d="M 2580 ${y-8} V ${y+8}" stroke="#dce5ed" stroke-width="5"/>`;}
 s.trains.forEach(t=>{
 const d=t.edge?Math.sign(t.edge[1]-t.edge[0]):0;
 const [x,y]=trainPoint(t);
 out+=`<g data-train="${t.id}" tabindex="0" role="button" aria-label="${t.id}を選択" style="cursor:pointer"><rect x="${x-21}" y="${y-10}" width="42" height="20" rx="4" fill="${t.id===s.selected?'#82d6b8':'#365a71'}"/><text x="${x}" y="${y+5}" text-anchor="middle" fill="${t.id===s.selected?'#0c2425':'#e7f3f8'}" font-size="14">${t.id}${t.dir===1?'→':'←'}</text></g>`;
 });
 const t=s.trains.find(t=>t.id===s.selected),e=equipment[t.at];
 const availability=e.platforms.map(p=>`<tr><td>${p.number}番</td>${[-1,1].map(d=>{const a=routeAvailability(s,e.at,p.number,d);return `<td>${d===1?'東':'西'}：${a.status}<br>${a.reason}</td>`;}).join('')}</tr>`).join('');
 return out+'</svg>'+`<section class="routeavailability"><h3>${e.name}：出発経路の可用性（信号現示ではありません）</h3><table><thead><tr><th>番線</th><th>西向き</th><th>東向き</th></tr></thead><tbody>${availability}</tbody></table></section>`+`<p class="trackdetail">${t.depotTrack?'森ヶ丘車庫'+t.depotTrack+'留置線（旅客番線ではありません）：準備・出庫経路と喉部鎖錠が必要':t.depotMove?'車庫'+t.depotMove.track+'線 ↔ 森ヶ丘'+t.depotMove.platform+'番：許可された出入庫移動中':e.name+t.platform+'番線：出発進路 '+[-1,1].map(d=>route(t.at,t.platform,'departure',d)?`${d===1?'東':'西'}向き信号・進路あり`:`${d===1?'東':'西'}向き信号・進路なし`).join(' / ')}。中立の枠記号＋矢印は信号設備と方向（実現示は非表示）、灰色長方形はホーム、端の縦線は車止め。到着予約は進入・続行方向を満たす空き番線（終着は折返可能番線を優先）。</p>`;
}
export function trainPoint(t){
 if(t.depotTrack)return [2480,330+(t.depotTrack-1)*36];
 if(!t.edge&&!t.depotMove)return [stationX(t.at),platformY(t.platform)];
 const segments=[...equipment.flatMap(e=>e.segments),...yardEquipment.segments];let ids,cursor,fraction;
 if(t.depotMove){ids=t.depotMove.route.path;cursor=t.depotMove.kind==='depotOut'?[2580,330+(t.depotMove.track-1)*36]:[stationX(7)+48,platformY(t.platform)];fraction=(3-t.depotMove.remaining)/3;}
 else {const d=Math.sign(t.edge[1]-t.at),out=equipment[t.at].routes.find(r=>r.id===t.departureRoute),into=equipment[t.edge[1]].routes.find(r=>r.id===t.arrivalRoute);ids=[...out.path,'block',...into.path];segments.push({id:'block',a:[stationX(t.at)+d*120,90],b:[stationX(t.edge[1])-d*120,90]});cursor=[stationX(t.at)-d*48,platformY(t.platform)];fraction=(3-t.remaining)/3;}
 const lines=[];for(const id of ids){const seg=segments.find(x=>x.id===id);if(!seg)throw Error('描画経路の線分欠損 '+id);const eq=(a,b)=>a[0]===b[0]&&a[1]===b[1];const end=eq(cursor,seg.a)?seg.b:eq(cursor,seg.b)?seg.a:null;if(!end)throw Error('描画経路の不連続 '+id);lines.push({a:cursor,b:end,length:Math.hypot(end[0]-cursor[0],end[1]-cursor[1])});cursor=end;}
 let dist=lines.reduce((n,l)=>n+l.length,0)*fraction;for(const l of lines){if(dist<=l.length){const f=dist/l.length;return [l.a[0]+(l.b[0]-l.a[0])*f,l.a[1]+(l.b[1]-l.a[1])*f];}dist-=l.length;}return cursor;
}
const time=v=>v==null?'—':clock(v);
export const duration=n=>`${Math.floor(n/60)}時間${n%60}分`;
const selected=(s,id)=>id===s.selected?'selected':'';
function formationHistory(s,t){const entries=s.history.filter(h=>(h.msg.startsWith(t.id+' ')||h.msg.startsWith(t.formation+' '))&&!h.msg.includes('臨時運行')).map(h=>({...h}));for(const a of s.actual.filter(a=>a.formation===t.formation&&a.actualDeparture!=null)){const r=s.timetable.find(r=>r.id===a.id);entries.push({time:a.actualDeparture,msg:`${a.id} ${stations[r.origin]}→${stations[s.plans.find(p=>p.id===r.id).dest]} / ${a.crew} / ${a.status} · 最終実着${time(a.stops.at(-1)?.arrival)}`});}return entries.sort((a,b)=>a.time-b.time).map(h=>`<tr><td>${clock(h.time)}</td><td>${h.msg}</td></tr>`).join('');}

function stationTable(s,r,p,a){let knownBlocked=false;const d=Math.sign(r.dest-r.origin);return `<table class="stop-table"><thead><tr><th>駅</th><th>所定着</th><th>所定発</th><th>変更着</th><th>変更発</th><th>実着</th><th>実発</th><th>番線</th></tr></thead><tbody>${r.stops.map(x=>{const y=a.stops.find(y=>y.at===x.at),inPlan=(x.at-r.origin)*d<=(p.dest-r.origin)*d;const crosses=(r.origin<=3&&x.at>=4)||(r.origin>=4&&x.at<=3);if(crosses&&s.phase==='区間閉鎖'||crosses&&s.phase==='片方向再開'&&d<0)knownBlocked=true;const uncertain=p.hold||knownBlocked;return `<tr><th>${stations[x.at]}</th><td>${time(x.arrival)}</td><td>${time(x.departure)}</td><td>${!inPlan?'運休':uncertain?'未定':time(x.arrival)}</td><td>${!inPlan?'運休':uncertain?'未定':x.at===p.dest?'—':time(x.departure)}</td><td>${time(y?.arrival)}</td><td>${time(y?.departure)}</td><td>${y?.platform??'—'}</td></tr>`;}).join('')}</tbody></table>`;}
function serviceRows(s,rows,links){return rows.map(r=>{const p=s.plans.find(p=>p.id===r.id),a=s.actual.find(a=>a.id===r.id),next=links.find(x=>x.id===r.id);return `<tr class="${s.selectedService===r.id?'selected':''}"><td><button data-pick="${p.train}" data-pickservice="${r.id}">${r.id}</button><div>${r.departure<s.time?(a.status==='運行中'?'現在':'過去'):'次便'}</div></td><td>${clock(r.departure)} ${stations[r.origin]}→${stations[r.dest]}<br>${r.crew||'臨時'}</td><td>${p.train} →${stations[p.dest]}<br><button data-pickcrew="${p.crew||a.crew||''}">${p.crew||'現地選定'}</button> ${p.hold?'抑止':''}${p.cancel?'運休':''}</td><td>${a.status}<br>発 ${time(a.actualDeparture)} / ${a.crew||'—'}</td><td>${a.reason||next?.reason||'実績確定'}</td></tr><tr class="stop-detail"><td colspan="5"><details data-service="${r.id}"><summary>${r.id} 駅別の比較表</summary>${stationTable(s,r,p,a)}</details></td></tr>`;}).join('');}
export function timetableHTML(s){const links=s.started?connections(s):[];return s.trains.map(t=>{const rows=s.timetable.filter(r=>s.plans.find(p=>p.id===r.id).train===t.id&&r.departure<=s.time+72).sort((a,b)=>a.departure-b.departure),recent=rows.filter(r=>r.departure>=s.time-36||s.actual.find(a=>a.id===r.id).status==='運行中'),past=rows.filter(r=>!recent.includes(r));const child=rr=>`<table class="service-table"><thead><tr><th>便 / 時期</th><th>元所定</th><th>変更・担当</th><th>実績</th><th>接続・制約</th></tr></thead><tbody>${serviceRows(s,rr,links)}</tbody></table>`;return `<section class="family ${selected(s,t.id)}"><h3><button data-pick="${t.id}">${t.formation} / 運用${t.id}</button> <span>${t.service||'次便待機'} · ${t.depotTrack?'車庫留置'+t.depotTrack+'線':t.edge?stations[t.at]+'→'+stations[t.edge[1]]:stations[t.at]+t.platform+'番'}</span></h3>${recent.length?child(recent):'<p>所定営業便なし。車庫の予備編成。</p>'}<details data-service="origin-${t.id}"><summary>${t.formation} はなぜここにいる？ 出庫からの実履歴</summary><table><thead><tr><th>時刻</th><th>出入庫・運行指令</th></tr></thead><tbody>${formationHistory(s,t)}</tbody></table></details><details data-service="past-${t.id}"><summary>過去の便（朝の回送・営業を含む）${past.length}便</summary>${child(past)}</details></section>`;}).join('');}
export function preserveHTML(container,html){const opened=new Set([...container.querySelectorAll('details')].filter(d=>d.open).map(d=>d.dataset.service||d.dataset.crew));const top=container.scrollTop;container.innerHTML=html;container.querySelectorAll('details').forEach(d=>d.open=opened.has(d.dataset.service||d.dataset.crew));container.scrollTop=top;}
export function updateTimetable(container,s){preserveHTML(container,timetableHTML(s));}
export function crewHTML(s,evaluate,overtimeRecord){return s.crews.map(c=>{const e=evaluate(c,{now:s.time}),ot=overtimeRecord(c),next=s.timetable.find(r=>r.departure>=s.time&&s.plans.find(p=>p.id===r.id).crew===c.id),t=s.trains.find(t=>t.id===c.train||t.id===c.ride);const values=[['実働',duration(c.todayWork)],['自由休憩',duration(c.breakMinutesActual)],['連続乗務',duration(c.continuousDrivingMinutes)+' / 上限3時間'],['評価超勤',duration(c.overtimeMinutes)+'（重複除外）'],['日 / 月 / 年 時間外',[e.dayOT,e.month,e.year].map(duration).join(' / ')],['最小協定残',duration(Math.max(0,e.remaining))],['今プレイ 法定 / 終業超過',duration(ot.statutory)+' / '+duration(ot.end)],['休憩不足予測',duration(e.breakNeeded)]];const segments=[...c.initialSegments,...c.dutySegments];return `<details data-crew="${c.id}" class="family ${t?.id===s.selected||s.selectedCrew===c.id?'selected':''}"><summary><button data-pickcrew="${c.id}">${c.id} ${c.name}</button> ${c.ended?'終業済み':s.time<c.dutyStart?'勤務前':c.rest?'自由休憩':c.train?'乗務・準備 '+c.train:c.ride?'便乗 '+c.ride:'待機（実働）'} / ${c.at==null?'列車移動中':stations[c.at]} · 実働${duration(c.todayWork)} · 次 ${next?.id||'なし'}</summary><table class="value-table"><tbody>${values.map(([k,v])=>`<tr><th>${k}</th><td>${v}</td></tr>`).join('')}</tbody></table><p>勤務 ${clock(c.dutyStart)}〜${clock(c.plannedDutyEnd)} / ${e.classification} ${e.errors.concat(e.safety).join(' / ')}</p><h4>勤務区間の実績（朝から連続）</h4><table><thead><tr><th>開始</th><th>終了</th><th>業務</th><th>区分 / 長さ</th></tr></thead><tbody>${segments.map(x=>`<tr><td>${clock(x.start)}</td><td>${clock(x.end)}</td><td>${{driving:'乗務・出入庫',standby:'指示待機',preparation:'点呼・準備・後処理',riding:'業務便乗',break:'解放された休憩'}[x.kind]}</td><td>${x.work?'実働':'自由休憩'} ${duration(x.end-x.start)}</td></tr>`).join('')}</tbody></table><h4>所定の担当便・途中休憩</h4><table><tr><th>便</th><th>出発</th><th>担当区間</th></tr>${s.timetable.filter(r=>r.crew===c.id).map(r=>`<tr><td><button data-pick="${s.plans.find(p=>p.id===r.id).train}" data-pickservice="${r.id}">${r.id}</button></td><td>${clock(r.departure)}</td><td>${stations[r.origin]}→${stations[r.dest]}</td></tr>`).join('')}${c.plannedBreaks.map(b=>`<tr><td>自由休憩予定</td><td>${clock(b.start)}〜${clock(b.end)}</td><td>担当後・実際の所在地で解放</td></tr>`).join('')}</table><details data-crew="law-${c.id}"><summary>資格・協定・過去履歴</summary><table class="value-table"><tr><th>資格</th><td>${c.qualifications.join(' / ')} / ${c.fitForDuty?'適性有効':'乗務不可'}</td></tr><tr><th>所属基地 / 現在地</th><td>森ヶ丘 / ${c.at==null?'乗車列車':stations[c.at]}</td></tr><tr><th>08:00先行実績（採点除外）</th><td>実働${duration(c.startLedger.work)} / 休憩${duration(c.startLedger.break)}</td></tr><tr><th>BASE協定</th><td>日2時間 / 月45時間 / 年360時間・特別条項なし</td></tr>${c.weekDays.map(d=>`<tr><th>${d.date}</th><td>実働${duration(d.work)} / 休憩${duration(d.break)}</td></tr>`).join('')}</table></details></details>`;}).join('');}
export function depotHTML(s){return `<section class="family"><h3>森ヶ丘車庫 · 西喉部に接続 · 留置4線 / 1線1編成</h3><table><thead><tr><th>留置線</th><th>収容編成</th><th>準備 / 出庫</th><th>接続経路</th></tr></thead><tbody>${s.depot.trackIDs.map((id,i)=>{const t=s.trains.find(t=>t.depotTrack===i+1||t.depotMove?.track===i+1);return `<tr><th>${i+1}線</th><td>${t?`<button data-pick="${t.id}">${t.formation} / ${t.id}</button>`:'空き'}</td><td>${t?.depotMove?'移動あと'+t.depotMove.remaining+'分':t?.busy?'準備あと'+t.busy+'分':t?.prepared?'準備済み':'車両準備5分＋出庫3分'}</td><td>${s.trains.some(t=>t.depotMove||t.edge&&t.at===7)?'森ヶ丘西喉部使用中':'経路未設定'} / 旅客進路と鎖錠共有</td></tr>`;}).join('')}</tbody></table></section>`;}
export function morningHTML(s){return `<details data-service="morning"><summary>04:00から08:00までの実際の引継ぎ履歴</summary><p>点呼04:10、車両準備、出庫、回送の後、05:24から営業開始。所属車庫と現在位置は別です。</p><table><thead><tr><th>時刻</th><th>実行結果</th></tr></thead><tbody>${s.morning.history.map(h=>`<tr><td>${clock(h.time)}</td><td>${h.msg}</td></tr>`).join('')}</tbody></table><table><thead><tr><th>編成</th><th>朝の便</th><th>出発実績</th><th>担当</th><th>状態</th></tr></thead><tbody>${s.morning.actual.slice().sort((a,b)=>a.actualDeparture-b.actualDeparture).map(a=>`<tr><td>${a.formation}</td><td>${a.id}</td><td>${clock(a.actualDeparture)}</td><td>${a.crew}</td><td>${a.status}（08:00時点）</td></tr>`).join('')}</tbody></table></details>`;}
