import {equipment,route,canReverse,reverseReason} from './equipment.js';
import {profile,evaluate,workMinute,breakMinute,overtimeRecord} from './labor.js';
export {equipment,canReverse};
export const VERSION=7, LIMIT=180, END=288, CYCLE=72;
export const stations=['中央','桜町','学園前','川原','東川原','丘の上','新都心','森ヶ丘'];
export const capacities=[3,2,4,2,3,2,4,3],hubs=[0,7],reliefStations=[0,2,4,6,7];
export function schedule(){const rows=[];for(let c=0;c<5;c++)for(const [offset,origin,dest,train] of [[0,0,7,'T1'],[36,7,0,'T1'],[32,0,2,'T2'],[44,2,0,'T2']]){const departure=c*72+offset,d=Math.sign(dest-origin);rows.push({id:`${train==='T1'?'A':'B'}${String(departure).padStart(3,'0')}`,train,formation:train==='T1'?'F1':'F2',crew:train==='T1'?`C${(Math.floor(departure/36)%3)+1+(departure>=288?8:0)}`:`C${5+c%2+(departure>=288?8:0)}`,origin,dest,departure,stops:[{at:origin,arrival:null,departure},...Array.from({length:Math.abs(dest-origin)},(_,i)=>({at:origin+d*(i+1),arrival:departure+3+i*4,departure:i===Math.abs(dest-origin)-1?null:departure+4+i*4}))]});}return rows.sort((a,b)=>a.departure-b.departure);}
function crewInitial(i,at){
 const successor=i>=8,k=i%8,id=`C${i+1}`,rows=schedule().filter(r=>r.crew===id&&(successor?r.departure>=288:r.departure<288));
 if(successor&&rows.length)at=rows[0].origin;
 const end=successor?740+rows.filter(r=>hubs.includes(r.dest)).length*30:rows.length?Math.max(...rows.map(r=>r.stops.at(-1).arrival+2)):288;
 const breaks=rows.filter(r=>hubs.includes(r.dest)).map(r=>({start:r.stops.at(-1).arrival+2,end:Math.min(end,r.stops.at(-1).arrival+32)})).filter(x=>x.end>x.start);if(successor)breaks.push({start:480,end:540});
 const work=successor?0:480-end+breaks.reduce((n,b)=>n+b.end-b.start,0),initialBreak=successor?0:60;
 const initialSegments=successor?[]:[{start:-work-60,end:-work-30,kind:'standby',work:true},{start:-work-30,end:-work+30,kind:'break',work:false},{start:-work+30,end:0,kind:'standby',work:true}];
 const history=[];for(let date=Date.UTC(2026,3,1);date<Date.UTC(2026,9,4);date+=86400000){const day=new Date(date),iso=day.toISOString().slice(0,10),recent=iso>='2026-09-28';const work=recent?(iso<='2026-10-01'?420:0):(day.getUTCDay()>0&&day.getUTCDay()<6?480:0);history.push({date:iso,work,break:work?60:0,holiday:day.getUTCDay()===6,start:work?'07:00':null,end:work?(work===480?'16:00':'15:00'):null});}
 const weekDays=history.filter(d=>d.date>='2026-09-28');
 return {id,name:['青木','泉','小野','加藤','佐野','高田','中村','林'][k]+(successor?'（後続）':''),role:'運転士',base:at,at,train:null,ride:null,locationState:successor?'beforeDuty':'standby',rest:0,pendingBreak:0,availableAt:successor?200:0,releaseAt:0,breakRun:0,duty:0,dutyStart:successor?200:-work-60,plannedDutyEnd:end,previousDutyEnd:-3900,todayWork:work,weekDays,monthOvertime:0,monthHoliday:0,yearOvertime:0,previousFiveMonths:[0,0,0,0,0],holiday:false,breakMinutesActual:initialBreak,continuousDrivingMinutes:0,overtimeMinutes:0,dutySegments:[],initialSegments,plannedBreaks:breaks,qualifications:['青葉線運転士'],qualificationUntil:700,fitForDuty:true,agreement:{filed:true,covered:true,validFrom:(Date.UTC(2026,3,1)-Date.UTC(2026,9,4,8))/60000,validUntil:(Date.UTC(2027,2,31,23,59)-Date.UTC(2026,9,4,8))/60000},historyAsOf:0,history,monthHistory:history.filter(d=>d.date.startsWith('2026-10')),yearHistory:history,startLedger:{work,break:initialBreak,month:0,year:0},scheduledDuty:{start:successor?200:-work-60,end,initialSegments,breaks,services:rows.map(r=>r.id),totalWork:480},dutyPlan:rows.map(r=>r.id+' → '+clock(r.stops.at(-1).arrival+2)+'後処理終了').join(' / ')|| (successor?'11:20始業・後続所定便担当':'予備待機・12:48終業'),ended:false};
}
export function dutyForecast(distance,{reverse=false,handover=false}={}){return {extra:distance*3+Math.max(0,distance-1)+2+(reverse?3:0)+(handover?2:0),driving:distance*3};}
export function createState({mode='incident'}={}){const timetable=schedule();return {version:VERSION,company:structuredClone(profile),mode,time:0,started:false,ended:false,phase:'導入',selected:'T1',timetable,plans:timetable.map(r=>({id:r.id,dest:r.dest,train:r.train,crew:r.crew,hold:false,cancel:false,mode:'旅客'})),actual:timetable.map(r=>({id:r.id,status:'未発車',formation:null,crew:null,actualDeparture:null,stops:[],reason:''})),trains:[[0,1,1],[0,2,1],[7,2,-1],[7,3,-1]].map(([at,platform,dir],i)=>({id:`T${i+1}`,formation:`F${i+1}`,at,platform,dir,crew:null,edge:null,reserved:null,remaining:0,busy:0,dest:null,origin:at,service:null,departureRoute:null,arrivalRoute:null,arrivalDirection:null,held:false,auto:true,mode:'旅客',onboard:0,passengers:[],riders:[]})),crews:[0,7,0,7,0,0,7,0,0,7,0,7,0,0,7,0].map((at,i)=>crewInitial(i,at)),formations:[0,0,7,7].map((at,i)=>({id:`F${i+1}`,train:`T${i+1}`,at,edge:null,status:'待機'})),waiting:Array(8).fill(0),queues:[],nextPassenger:1,nextExtra:1,stats:{wait:0,transported:0,cancelled:0,blocked:0,overtime:0},important:[],history:[],notice:'所定ダイヤ準備済み。開始後は無操作で運行します。',recoveryAt:null,stableSince:null,violations:[]};}
export function clock(n){const m=480+n;return `${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;}
export function phase(s){if(s.forecast)return s.knownPhase;return s.mode==='normal'?'平常運転':s.time<5?'平常運転':s.time<20?'区間閉鎖':s.time<65?'片方向再開':'全線再開';}
export function closed(s,a,b){return Math.min(a,b)===3&&(phase(s)==='区間閉鎖'||phase(s)==='片方向再開'&&b<a);}
function log(s,msg){s.history.push({time:s.time,msg});s.notice=msg;}
function notify(s,msg){s.important.push({time:s.time,msg,acknowledged:false});log(s,msg);}
export function platformUse(s,n){return s.trains.filter(t=>t.edge?t.edge[1]===n:t.at===n).map(t=>({id:t.id,platform:t.edge?t.reserved:t.platform,reserved:!!t.edge}));}
export function arrivalPlatform(s,t,n,d){const used=platformUse(s,n).map(u=>u.platform);const reverse=n===t.dest;const candidates=equipment[n].platforms.filter(p=>!used.includes(p.number)&&route(n,p.number,'arrival',d)&&route(n,p.number,'departure',reverse?-d:d));candidates.sort((a,b)=>Number(!!route(n,b.number,'departure',-d))-Number(!!route(n,a.number,'departure',-d)));return candidates[0]?.number??null;}
export function departureReason(s,t,d=Math.sign(t.dest-t.at),n=t.at+d){const out=route(t.at,t.platform,'departure',d);if(!out)return `${stations[t.at]}${t.platform}番線には${d===1?'東':'西'}向き出発信号／列車進路がありません。`;if(closed(s,t.at,n))return `${stations[t.at]}―${stations[n]}はこの方向に閉鎖中です。`;if(s.trains.some(x=>x!==t&&x.edge&&Math.min(...x.edge)===Math.min(t.at,n)))return '隣接単線閉塞が占有中です。';const p=arrivalPlatform(s,t,n,d);if(p===null)return `${stations[n]}の対応番線が満杯、または続行／折返進路がありません。`;const locks=[...out.locks,...route(n,p,'arrival',d).locks];if(s.trains.some(x=>x!==t&&x.edge&&[x.departureRoute,x.arrivalRoute].some(id=>equipment.flatMap(e=>e.routes).find(r=>r.id===id)?.locks.some(l=>locks.includes(l)))))return '駅の進路鎖錠資源が使用中です。';return '';}
function nextRow(s,t){return s.timetable.slice().sort((a,b)=>a.departure-b.departure).find(r=>s.plans.find(p=>p.id===r.id).train===t.id&&!['完了','短縮完了','運休'].includes(s.actual.find(a=>a.id===r.id).status));}
export function options(s,id){const train=s.trains.find(t=>t.id===id);return {train,crew:s.crews.find(c=>c.id===train?.crew)};}
function eligible(c,s,forecast={extra:0,driving:0}){if(c.ended||s.time<c.dutyStart||c.rest||c.pendingBreak||c.releaseAt>s.time||c.train||c.ride)return false;return evaluate(c,{...forecast,now:s.time}).allowed;}
function turnReason(t){return reverseReason(t);}
export function check(s,id,action,arg={}){const t=s.trains.find(t=>t.id===id);if(!t)return '編成運用がありません。';if(!s.started||s.ended)return '開始前または結果表示中です。';const r=arg.service?s.timetable.find(r=>r.id===arg.service):nextRow(s,t),p=s.plans.find(p=>p.id===r?.id);
 if(['hold','resume','cancel','restorePlan','shorten','assign'].includes(action)){
 if(!r||!p)return '変更対象便がありません。';const a=s.actual.find(a=>a.id===r.id),live=s.trains.find(x=>x.service===r.id);if(action==='assign'&&live)return '運行中便の編成割当は変更できません。現地の乗務交代は駅抑止中の専用操作を使ってください。';if(action==='restorePlan'&&live&&live.id!==r.train)return '代走便の運行中は元編成へ戻せません。終着後の次便を変更してください。';if(['完了','短縮完了','運休'].includes(a.status))return '確定済みの実績は変更できません。';
 if(action==='shorten'){if(!Number.isInteger(arg.dest)||arg.dest<Math.min(r.origin,r.dest)||arg.dest>Math.max(r.origin,r.dest)||arg.dest===r.origin)return '所定区間内の短縮終着を選んでください。';const d=Math.sign(r.dest-r.origin);if(live&&((arg.dest-live.at)*d<0||arg.dest===live.at&&live.edge))return '進行方向前方の駅を選んでください。';if(!equipment[arg.dest].platforms.some(x=>route(arg.dest,x.number,'arrival',d)&&route(arg.dest,x.number,'departure',-d)))return `${stations[arg.dest]}には到着後の逆向き出発経路がありません。`;if(live&&live.at===arg.dest&&!live.edge&&!route(live.at,live.platform,'departure',-d))return `${stations[live.at]}${live.platform}番線には逆向き出発信号／列車進路がありません。`;if(live?.edge&&live.edge[1]===arg.dest&&!route(arg.dest,live.reserved,'departure',-d))return '予約済み番線から逆向きに出発できません。';}
 if(action==='assign'){const c=s.crews.find(c=>c.id===arg.crew);if(arg.crew&&(!c||c.at!==r.origin||!eligible(c,s,{...dutyForecast(Math.abs(p.dest-r.origin)),extra:Math.max(0,r.departure-s.time)+dutyForecast(Math.abs(p.dest-r.origin)).extra})))return '交代員の所在・休憩・資格・勤務枠が次便に適合しません。';if(t.edge||t.at!==r.origin)return '代走編成が所定始発駅にありません。';}
 return '';}
 if(action==='dispatch'){if(t.edge||t.dest!==null||t.busy)return '走行／準備／運行中です。';if(!Number.isInteger(arg.dest)||arg.dest<0||arg.dest>7||arg.dest===t.at)return '異なる行先を選んでください。';const d=Math.sign(arg.dest-t.at);if(t.dir!==d&&turnReason(t))return turnReason(t);if(!route(t.at,t.platform,'departure',d))return '現在番線の出発進路がありません。';if(!equipment[arg.dest].platforms.some(p=>route(arg.dest,p.number,'arrival',d)&&route(arg.dest,p.number,'departure',-d)))return '終着で戻る出発経路がありません。';if(!s.crews.some(c=>c.at===t.at&&eligible(c,s,dutyForecast(Math.abs(arg.dest-t.at),{reverse:t.dir!==Math.sign(arg.dest-t.at)}))))return 'この駅に移動・後処理まで勤務可能な乗務員がいません。';return '';}
 if(t.edge||t.busy)return '走行／準備中です。';if(action==='turn')return t.service?'便の運行中です。終着後に反転してください。':turnReason(t);if(action==='relief'){if(!t.service)return '乗務交代は担当便の駅抑止中に実施します。';if(!reliefStations.includes(t.at))return 'この駅に交代設備がありません。';const duration=dutyForecast(Math.abs(t.dest-t.at),{handover:true});return s.crews.some(c=>(!arg.crew||c.id===arg.crew)&&c.at===t.at&&eligible(c,s,duration))?'':'この駅に次の終着・後処理まで勤務可能な指定交代員がいません。';}if(action==='rest'){if(t.crew||t.dest!==null)return '運用中は自由休憩ではありません。終着・交代後に休憩します。';return '';}
 if(action==='transfer'){const c=s.crews.find(c=>c.id===arg.crew);return c&&c.at===t.at&&eligible(c,s,{extra:30,driving:0})?'':'この駅の待機乗務員を選んでください。';}
 if(action==='endBreak'){const c=s.crews.find(c=>c.id===arg.crew);return c&&c.rest>0&&c.at===t.at?'':'この駅の休憩中乗務員を選んでください。';}
 if(action==='break'){const c=s.crews.find(c=>c.id===arg.crew);return c&&c.at===t.at&&!c.train&&!c.ride&&!c.ended&&!c.rest&&!c.pendingBreak&&c.releaseAt<=s.time&&hubs.includes(t.at)?'':'拠点の業務未割当乗務員を選んでください。';}
 if(action==='retire'){const c=s.crews.find(c=>c.id===arg.crew);if(!c||c.train||c.ride||c.rest||c.pendingBreak||c.releaseAt>s.time)return '勤務／移動／休憩中は終業できません。';return evaluate(c,{complete:true,now:s.time}).errors.join(' / ');}
 return '対象操作がありません。';}
export function preview(s,id,action,arg={}){const t=s.trains.find(t=>t.id===id),r=arg.service?s.timetable.find(r=>r.id===arg.service):nextRow(s,t);const next=r?s.timetable.find(x=>x.departure>r.departure&&x.train===r.train):null;const p=s.plans.find(p=>p.id===r?.id),live=s.trains.find(x=>x.service===r?.id);
 const existing=['shorten','hold','resume'].includes(action);
 const origin=action==='assign'?r?.origin:existing?(live?.at??r?.origin):t?.at;
 const dest=action==='assign'?p?.dest:action==='shorten'?arg.dest:existing?p?.dest:action==='relief'?t?.dest:arg.dest??r?.dest??t?.at;
 const forecast=dutyForecast(Math.abs((dest??origin)-origin),{reverse:action==='dispatch'&&t.dir!==Math.sign(arg.dest-t.at),handover:action==='relief'});
 if(action==='assign')forecast.extra+=Math.max(0,(r?.departure??s.time)-s.time);
 const c=(existing?s.crews.find(c=>c.id===(live?.crew??p?.crew)):s.crews.find(c=>c.id===arg.crew))||s.crews.filter(c=>c.at===origin&&eligible(c,s,forecast)).sort((a,b)=>a.todayWork-b.todayWork||a.id.localeCompare(b.id))[0];
 const e=c?evaluate(c,{...forecast,now:s.time}):null;
 return {reason:check(s,id,action,arg),info:`${r?'対象 '+r.id+'（元の所定 '+clock(r.departure)+' '+stations[r.origin]+'→'+stations[r.dest]+'）':'臨時指令'}。${action==='shorten'?`短縮区間の旅客は目的地未着のまま待ちます。終着で3分反転、次便始発へ戻す必要があります。`:action==='hold'?'変更計画を抑止。再開指令まで自動処理で解除しません。':action==='dispatch'?'臨時運行：人車は列車で移動。所要＝駅間3分＋中間停車1分＋必要時反転3分。':'変更は所定を残して記録します。'} ${next?`次便 ${next.id} ${clock(next.departure)} ${stations[next.origin]}発。現在配置から接続可能か一覧で確認。`:''} ${e?`見込は既知の走行・停車・準備・後処理を算入、未確定の閉鎖待ちは延長の可能性。候補 ${c.id}：${e.classification} / 協定残${e.remaining}分 / 追加評価対象超勤見込${e.additionalOvertime}分（法定時間外${e.additionalStatutoryOvertime}／所定終業超過${e.additionalEndOvertime}、重複除外）（実績1分につき1点減点） / 休憩不足予測${e.breakNeeded}分。`:''}`};}
export function act(s,id,action,arg={}){const reason=check(s,id,action,arg);if(reason){s.notice=reason;return false;}const t=s.trains.find(t=>t.id===id),r=arg.service?s.timetable.find(r=>r.id===arg.service):nextRow(s,t),p=s.plans.find(p=>p.id===r?.id);
 if(action==='hold')p.hold=true;if(action==='resume')p.hold=false;
 if(action==='shorten'){p.dest=arg.dest;const live=s.trains.find(x=>x.service===r.id);if(live){live.dest=arg.dest;if(live.at===arg.dest&&!live.edge)finish(s,live);}}
 if(action==='restorePlan'){Object.assign(p,{dest:r.dest,hold:false,train:r.train,crew:r.crew,mode:'旅客'});const live=s.trains.find(x=>x.service===r.id);if(live)live.dest=r.dest;}
 if(action==='cancel'){p.cancel=true;const a=s.actual.find(a=>a.id===r.id);a.status='運休';s.stats.cancelled++;const live=s.trains.find(x=>x.service===r.id);if(live&&!live.edge)finish(s,live,false);}
 if(action==='assign'){p.train=id;p.crew=arg.crew||null;}
 if(action==='turn'){t.dir*=-1;t.busy=3;}
 if(action==='dispatch'){const d=Math.sign(arg.dest-t.at);if(t.dir!==d){t.dir=d;t.busy=3;}const extra={id:`X${s.nextExtra++}`,train:id,formation:t.formation,origin:t.at,dest:arg.dest,departure:s.time+t.busy,stops:[]};extra.stops=[{at:t.at,arrival:null,departure:extra.departure},...Array.from({length:Math.abs(arg.dest-t.at)},(_,i)=>({at:t.at+d*(i+1),arrival:extra.departure+3+i*4,departure:i===Math.abs(arg.dest-t.at)-1?null:extra.departure+4+i*4}))];s.timetable.push(extra);s.plans.push({id:extra.id,dest:arg.dest,train:id,crew:null,hold:false,cancel:false,mode:arg.mode==='回送'?'回送':'旅客'});s.actual.push({id:extra.id,status:'未発車',formation:null,crew:null,actualDeparture:null,stops:[],reason:''});}
 if(action==='transfer'){const c=s.crews.find(c=>c.id===arg.crew);c.ride=id;c.locationState='riding';t.riders.push(c.id);}
 if(action==='endBreak'){const c=s.crews.find(c=>c.id===arg.crew);c.rest=0;c.availableAt=s.time;c.breakRun=0;c.locationState='standby';}
 if(action==='break'){const c=s.crews.find(c=>c.id===arg.crew);c.rest=30;c.availableAt=s.time+30;c.breakRun=0;c.locationState='break';}
 if(action==='retire'){const c=s.crews.find(c=>c.id===arg.crew);c.ended=true;c.locationState='off';}
 if(action==='relief'){const old=s.crews.find(c=>c.id===t.crew);if(old){old.train=null;old.rest=0;old.releaseAt=s.time+2;old.pendingBreak=hubs.includes(t.at)?30:0;old.availableAt=old.releaseAt+old.pendingBreak;old.breakRun=0;old.locationState='preparation';}const c=s.crews.find(c=>(!arg.crew||c.id===arg.crew)&&c.at===t.at&&eligible(c,s,dutyForecast(Math.abs(t.dest-t.at),{handover:true})));t.crew=c.id;c.train=id;c.locationState='driving';t.busy=2;if(t.service){const a=s.actual.find(a=>a.id===t.service);a.crewChanges??=[];a.crewChanges.push({time:s.time,at:t.at,from:old?.id??null,to:c.id});a.crew=c.id;}}
 log(s,`${id} ${r?.id||''} ${{hold:'便抑止',resume:'抑止解除',shorten:'行先短縮',assign:'代走・乗員変更計画',restorePlan:'所定計画へ復元',cancel:'部分運休',dispatch:'臨時運行',turn:'反転準備',transfer:'便乗配置',relief:'現地乗務交代',break:'自由休憩開始',endBreak:'自由休憩中断',retire:'終業'}[action]} ${arg.dest===undefined?'':stations[arg.dest]} ${arg.crew||''}`);return true;}
function finish(s,t,completed=true){const a=s.actual.find(a=>a.id===t.service),r=s.timetable.find(r=>r.id===t.service);if(a&&completed)a.status=t.at===r.dest?'完了':'短縮完了';for(const p of t.passengers){p.at=t.at;s.queues.push(p);}t.passengers=[];t.onboard=0;const c=s.crews.find(c=>c.id===t.crew);if(c){c.train=null;c.at=t.at;c.rest=0;c.pendingBreak=hubs.includes(t.at)&&s.time+2<c.plannedDutyEnd?Math.min(30,c.plannedDutyEnd-s.time-2):0;c.releaseAt=s.time+2;c.availableAt=c.releaseAt+c.pendingBreak;c.breakRun=0;c.locationState='preparation';}for(const id of t.riders){const c=s.crews.find(c=>c.id===id);c.at=t.at;c.ride=null;c.locationState='standby';}t.riders=[];t.crew=null;t.dest=null;t.service=null;t.busy=3;if(canReverse(t))t.dir*=-1;}
function startService(s,t,r,p,a){if(t.edge||t.busy||t.service)return false;if(t.at!==r.origin){a.reason=`${t.formation}在${stations[t.at]}：未到所定始発${stations[r.origin]}、人車接続不足`;return false;}const d=Math.sign(p.dest-r.origin);if(t.dir!==d){if(!canReverse(t)){a.reason=turnReason(t);return false;}t.dir=d;t.busy=3;return false;}const duration=dutyForecast(Math.abs(p.dest-t.at));let c=p.crew?s.crews.find(c=>c.id===p.crew&&c.at===t.at&&eligible(c,s,duration)):s.crews.filter(c=>c.at===t.at&&eligible(c,s,duration)).sort((a,b)=>a.todayWork-b.todayWork||a.id.localeCompare(b.id))[0];if(!c){a.reason='始発駅に交代・後処理まで勤務可能な乗務員がいません。交代／運休を選択してください。';return false;}c.train=t.id;c.locationState='driving';t.crew=c.id;t.service=r.id;t.dest=p.dest;t.origin=r.origin;t.mode=p.mode;a.status='運行中';a.formation=t.formation;a.crew=c.id;return true;}
function depart(s,t){if(t.edge||t.busy||t.dest===null)return;const a=s.actual.find(a=>a.id===t.service),p=s.plans.find(p=>p.id===t.service);if(p.cancel){finish(s,t,false);return;}if(p.hold){a.reason='指令抑止中';return;}const d=Math.sign(t.dest-t.at),c=s.crews.find(c=>c.id===t.crew);let reason=departureReason(s,t,d);const e=evaluate(c,{...dutyForecast(Math.abs(t.dest-t.at)),now:s.time});if(!e.allowed)reason=e.errors.concat(e.safety).join(' / ');if(reason){if(a.reason!==reason&&!e.allowed)notify(s,`${t.id} ${a.id} 勤務／安全条件で抑止：${reason}。交代または運休してください。`);a.reason=reason;return;}a.reason='';if(a.actualDeparture===null){a.actualDeparture=s.time;a.stops.push({at:t.at,arrival:null,departure:s.time,platform:t.platform});}else {const stop=a.stops.at(-1);stop.departure=s.time;}
 if(t.mode==='旅客'){const boarding=s.queues.filter(p=>p.at===t.at&&Math.sign(p.dest-p.at)===d).slice(0,80-t.passengers.length);t.passengers.push(...boarding);const ids=new Set(boarding.map(p=>p.id));s.queues=s.queues.filter(p=>!ids.has(p.id));}
 t.onboard=t.passengers.length;t.reserved=arrivalPlatform(s,t,t.at+d,d);t.departureRoute=route(t.at,t.platform,'departure',d).id;t.arrivalRoute=route(t.at+d,t.reserved,'arrival',d).id;t.edge=[t.at,t.at+d];t.remaining=3;c.at=null;for(const id of t.riders)s.crews.find(c=>c.id===id).at=null;sync(s);}
function run(s){for(const t of s.trains){if(!t.service&&!t.busy&&!t.edge){const r=nextRow(s,t);if(r&&r.departure<=s.time){const p=s.plans.find(p=>p.id===r.id),a=s.actual.find(a=>a.id===r.id);if(!p.hold&&!p.cancel)startService(s,t,r,p,a);else a.reason='指令抑止中';}}depart(s,t);}sync(s);}
function sync(s){for(const t of s.trains){const f=s.formations.find(f=>f.id===t.formation);f.at=t.edge?null:t.at;f.edge=t.edge?[...t.edge]:null;f.status=t.edge?'走行':t.busy?'準備':'待機';}s.waiting=stations.map((_,at)=>s.queues.filter(p=>p.at===at).length);}
export function start(s){if(s.started)return;s.started=true;s.phase=phase(s);log(s,'所定自動運行開始。平常時の発車操作は不要です。');run(s);}
function demand(s){if(s.time%4)return;for(let at=0;at<8;at++){// 平常容量80人に対し、1周期の最大片方向需要は72人未満。
 const dest=(at+(Math.floor(s.time/4)%7)+1)%8;s.queues.push({id:s.nextPassenger++,origin:at,at,dest,born:s.time});}}
function recovered(s){if(s.mode==='normal')return false;const since=72*Math.floor((s.time-72)/72);if(since<72)return false;const rows=s.timetable.filter(r=>!r.id.startsWith('X')&&r.departure>=since&&r.departure<since+72);if(s.time<since+72||rows.length!==4)return false;return rows.every(r=>{const a=s.actual.find(a=>a.id===r.id),p=s.plans.find(p=>p.id===r.id);return p.dest===r.dest&&!p.hold&&!p.cancel&&a.status==='完了'&&a.actualDeparture===r.departure&&r.stops.slice(1).every(x=>{const real=a.stops.find(y=>y.at===x.at);return real?.arrival===x.arrival&&(x.departure===null||real.departure===x.departure);});})&&connections(s).filter(x=>x.departure>=since+72&&x.departure<since+144).every(x=>x.possible);}
export function connections(s){const rows=s.timetable.filter(r=>!r.id.startsWith('X')&&r.departure>=s.time&&r.departure<=s.time+72);const copy=JSON.parse(JSON.stringify(s));copy.forecast=true;copy.knownPhase=s.phase;copy.ended=false;const target=Math.max(s.time,...rows.map(r=>r.departure));while(copy.time<target)tick(copy);return rows.map(r=>{const a=copy.actual.find(a=>a.id===r.id),p=s.plans.find(p=>p.id===r.id);return {id:r.id,departure:r.departure,origin:r.origin,train:p.train,possible:a.actualDeparture===r.departure,reason:a.actualDeparture===r.departure?'現計画を継続した場合、人車・進路接続が成立':a.reason||'前便遅延／人車接続不足。所定時刻に発車不能'};});}
export function tick(s,count=1){if(!s.started||s.ended)return s;for(let k=0;k<count&&!s.ended;k++){s.time++;const ph=phase(s);if(ph!==s.phase){s.phase=ph;if(ph==='区間閉鎖'){for(const t of s.trains.filter(t=>t.service)){const p=s.plans.find(p=>p.id===t.service);p.hold=true;} }notify(s,ph==='区間閉鎖'?'現場通報：川原―東川原の設備故障、双方向閉鎖。運行中便を駅到着後に安全抑止しました。変更計画を確認し「抑止解除」を指令してください。退出中の列車は到着まで走行。':ph==='片方向再開'?'現場確認：川原→東川原のみ再開。西向き再開時刻は未確定。':'現場確認：全線の両方向運転が可能です。所定1周期と翌接続を確認してください。');}
 demand(s);s.stats.wait+=s.queues.length;for(const c of s.crews){if(c.ended||s.time<=c.dutyStart)continue;if(c.id.slice(1)*1>8&&!c.train&&!c.ride&&!c.rest&&!c.pendingBreak){const b=c.plannedBreaks.find(b=>b.start===s.time-1);if(b){c.rest=b.end-b.start;c.breakRun=0;c.locationState='break';}}if(c.pendingBreak&&s.time>c.releaseAt){c.rest=c.pendingBreak;c.pendingBreak=0;c.locationState='break';}if(c.rest){breakMinute(c,s.time);c.rest--;if(!c.rest)c.locationState='standby';}else {c.breakRun=0;workMinute(c,s.time,c.releaseAt>=s.time?'preparation':c.ride?'riding':c.train&&s.trains.find(t=>t.id===c.train)?.busy?'preparation':c.train&&s.trains.find(t=>t.id===c.train)?.edge?'driving':'standby');}const e=evaluate(c,{now:s.time});if(e.errors.length||e.safety.length){const msg=c.id+' '+e.errors.concat(e.safety).join('/');if(!s.violations.includes(msg))s.violations.push(msg);}}
 for(const t of s.trains){if(t.busy)t.busy--;if(t.edge){t.remaining--;if(!t.remaining){t.at=t.edge[1];t.platform=t.reserved;t.arrivalDirection=t.dir;t.edge=null;t.reserved=null;t.departureRoute=null;t.arrivalRoute=null;const a=s.actual.find(a=>a.id===t.service);a.stops.push({at:t.at,arrival:s.time,departure:null,platform:t.platform});const c=s.crews.find(c=>c.id===t.crew);c.at=t.at;for(const id of t.riders)s.crews.find(c=>c.id===id).at=t.at;const arrived=t.passengers.filter(p=>p.dest===t.at);s.stats.transported+=arrived.length;t.passengers=t.passengers.filter(p=>p.dest!==t.at);t.onboard=t.passengers.length;t.busy=1;if(t.at===t.dest||s.plans.find(p=>p.id===t.service).cancel)finish(s,t,!s.plans.find(p=>p.id===t.service).cancel);}}}
 for(const c of s.crews){if(!c.ended&&s.time>=c.plannedDutyEnd&&!c.train&&!c.ride&&c.releaseAt<=s.time){c.rest=0;c.pendingBreak=0;const e=evaluate(c,{complete:true,now:s.time});if(e.errors.length)s.violations.push(c.id+' '+e.errors.join('/'));c.ended=true;c.locationState='off';}}run(s);s.stats.overtime=s.crews.reduce((n,c)=>n+c.overtimeMinutes,0);if(!s.forecast&&!s.recoveryAt&&recovered(s)){s.recoveryAt=s.time;log(s,'所定1周期の全停車・発着と翌接続を確認。運用復旧達成。');}if(!s.forecast&&s.time>=END){s.ended=true;notify(s,'固定観察時間が終了しました。未完了勤務は継続予測として扱い、自動退勤しません。');}}
 return s;}
export function serviceDelay(s,r){const a=s.actual.find(a=>a.id===r.id);return Math.max(0,(a.actualDeparture??s.time)-r.departure,...a.stops.map(x=>x.arrival===null?0:x.arrival-(r.stops.find(y=>y.at===x.at)?.arrival??x.arrival)));}
export function playerInfo(s){return {constraint:s.phase==='区間閉鎖'?'川原―東川原：双方向閉鎖':s.phase==='片方向再開'?'川原→東川原のみ / 西向き閉鎖':'全区間正常に通行可能',latest:s.important.at(-1)?.msg||'所定自動運行。現在の現場制約変更なし',reports:s.important.map(x=>({...x}))};}
export function result(s){return {success:!!s.recoveryAt&&!s.violations.length,wait:s.stats.wait,transported:s.stats.transported,unfinished:s.queues.length+s.trains.reduce((n,t)=>n+t.passengers.length,0),overtime:s.stats.overtime,score:Math.round(s.stats.transported*10-s.stats.wait/100-s.stats.overtime+(s.recoveryAt?500+(END-s.recoveryAt)*3:0)),violations:s.violations};}
export function serialize(s){return JSON.stringify(s);}
export function validate(s){const fail=msg=>{throw Error('保存形式・状態が不正：'+msg);};if(s?.forecast||'knownPhase' in (s||{}))fail('内部予測状態は保存できません');if(!s||s.version!==VERSION)fail('バージョンが異なります');if(!['normal','incident'].includes(s.mode)||!Number.isInteger(s.time)||s.time<0||s.time>END)fail('時刻／モード');const base=createState({mode:s.mode});for(const key of ['trains','crews','formations','timetable','plans','actual','queues','waiting','history','important','violations'])if(!Array.isArray(s[key]))fail(key+'の形式');if(JSON.stringify(s.company)!==JSON.stringify(base.company))fail('会社プロフィール');for(const key of Object.keys(base))if(!(key in s))fail(key);const prescribed=s.timetable.filter(r=>!r.id.startsWith('X'));if(JSON.stringify(prescribed)!==JSON.stringify(schedule()))fail('元所定ダイヤの変更');if(s.timetable.length>100||s.history.length>10000||s.queues.length>10000)fail('保存サイズ');if(s.trains.length!==4||s.crews.length!==16||s.formations.length!==4||s.plans.length!==s.timetable.length||s.actual.length!==s.timetable.length)fail('資源数／便数');if(s.phase!==(s.started?phase(s):'導入')||typeof s.started!=='boolean'||typeof s.ended!=='boolean'||!s.trains.some(t=>t.id===s.selected))fail('進行状態');
 for(const r of s.timetable){const p=s.plans.filter(x=>x.id===r.id),a=s.actual.filter(x=>x.id===r.id);if(p.length!==1||a.length!==1||!s.trains.some(t=>t.id===p[0].train)||!Number.isInteger(p[0].dest)||p[0].dest<Math.min(r.origin,r.dest)||p[0].dest>Math.max(r.origin,r.dest)||p[0].dest===r.origin||!['未発車','運行中','完了','短縮完了','運休'].includes(a[0].status))fail('便計画');if(typeof p[0].hold!=='boolean'||typeof p[0].cancel!=='boolean'||!['旅客','回送'].includes(p[0].mode)||!(p[0].crew===null||s.crews.some(c=>c.id===p[0].crew))||!Array.isArray(a[0].stops)||!(a[0].actualDeparture===null||Number.isInteger(a[0].actualDeparture)&&a[0].actualDeparture>=r.departure&&a[0].actualDeparture<=s.time)||typeof a[0].reason!=='string')fail('計画／実績形式');for(const x of a[0].stops)if(!Number.isInteger(x.at)||x.at<0||x.at>7||!(x.arrival===null||Number.isInteger(x.arrival)&&x.arrival<=s.time&&x.arrival>=0)||!(x.departure===null||Number.isInteger(x.departure)&&x.departure<=s.time&&x.departure>=0))fail('停車実績');if(!equipment[p[0].dest]?.platforms.some(x=>route(p[0].dest,x.number,'arrival',Math.sign(r.dest-r.origin))&&route(p[0].dest,x.number,'departure',-Math.sign(r.dest-r.origin))))fail('終着進路');}
 const blocks=[],locks=[],people=[];for(let i=0;i<4;i++){const t=s.trains[i],f=s.formations[i];if(t.id!==`T${i+1}`||t.formation!==`F${i+1}`||f.id!==t.formation||t.at<0||t.at>7||!Number.isInteger(t.at)||![-1,1].includes(t.dir)||!equipment[t.at].platforms.some(p=>p.number===t.platform)||!Number.isInteger(t.busy)||t.busy<0||t.busy>3)fail('編成位置');if(f.at!==(t.edge?null:t.at)||JSON.stringify(f.edge)!==JSON.stringify(t.edge))fail('編成保存則');if(t.service){const a=s.actual.find(a=>a.id===t.service),p=s.plans.find(p=>p.id===t.service);if(!a||!p||p.train!==t.id||a.formation!==t.formation||a.crew!==t.crew||!t.crew||p.dest!==t.dest||!['運行中','運休'].includes(a.status))fail('運行と計画');}else if(t.crew||t.dest!==null||t.edge)fail('担当運行');if(t.edge){const d=t.edge[1]-t.at;if(t.edge[0]!==t.at||Math.abs(d)!==1||d!==t.dir||!Number.isInteger(t.remaining)||t.remaining<1||t.remaining>3||route(t.at,t.platform,'departure',d)?.id!==t.departureRoute||route(t.edge[1],t.reserved,'arrival',d)?.id!==t.arrivalRoute||!route(t.edge[1],t.reserved,'departure',t.edge[1]===t.dest?-d:d))fail('走行進路');blocks.push(Math.min(...t.edge));for(const id of [t.departureRoute,t.arrivalRoute])locks.push(...equipment.flatMap(e=>e.routes).find(r=>r.id===id).locks);}else {if(t.remaining!==0||t.reserved!==null)fail('停車');if(t.arrivalDirection!==null&&(!route(t.at,t.platform,'arrival',t.arrivalDirection)||t.dir!==t.arrivalDirection&&!route(t.at,t.platform,'departure',t.dir)))fail('反転信号');}for(const id of [t.crew,...t.riders].filter(Boolean))people.push(id);if(t.onboard!==t.passengers.length||t.passengers.length>80)fail('旅客保存');}
 for(const arr of [blocks,locks,people])if(new Set(arr).size!==arr.length)fail('閉塞／進路／人員二重使用');for(let n=0;n<8;n++){const slots=platformUse(s,n).map(x=>x.platform);if(new Set(slots).size!==slots.length)fail('番線重複');}
 for(let i=0;i<16;i++){const c=s.crews[i];if(c.id!==`C${i+1}`||!Number.isInteger(c.todayWork)||c.todayWork<0||!Number.isInteger(c.rest)||c.rest<0||c.rest>30||!Array.isArray(c.dutySegments)||!Array.isArray(c.qualifications)||!c.agreement||!Array.isArray(c.weekDays)||!Array.isArray(c.previousFiveMonths)||c.previousFiveMonths.length!==5)fail('勤務台帳');if(c.train||c.ride){const t=s.trains.find(t=>t.id===(c.train||c.ride));if(!t||c.at!==(t.edge?null:t.at)||c.train&&t.crew!==c.id||c.ride&&!t.riders.includes(c.id)||c.rest||c.ended)fail('乗務員位置');}else if(!Number.isInteger(c.at)||c.at<0||c.at>7)fail('乗務員所在');const worked=c.dutySegments.filter(x=>x.work).reduce((n,x)=>n+x.end-x.start,0),breaks=c.dutySegments.filter(x=>x.kind==='break').reduce((n,x)=>n+x.end-x.start,0);const initial=base.crews[i];if(JSON.stringify(c.startLedger)!==JSON.stringify(initial.startLedger)||JSON.stringify(c.initialSegments)!==JSON.stringify(initial.initialSegments)||JSON.stringify(c.history)!==JSON.stringify(initial.history)||JSON.stringify(c.weekDays)!==JSON.stringify(initial.weekDays)||JSON.stringify(c.monthHistory)!==JSON.stringify(initial.monthHistory)||JSON.stringify(c.yearHistory)!==JSON.stringify(initial.yearHistory)||JSON.stringify(c.previousFiveMonths)!==JSON.stringify(initial.previousFiveMonths)||JSON.stringify(c.scheduledDuty)!==JSON.stringify(initial.scheduledDuty)||c.dutyStart!==initial.dutyStart||c.plannedDutyEnd!==initial.plannedDutyEnd)fail('先行履歴／所定勤務改変');if(c.todayWork!==c.startLedger.work+worked||c.breakMinutesActual!==c.startLedger.break+breaks)fail('勤務実績整合');}
 for(const c of s.crews){for(const key of ['todayWork','monthOvertime','yearOvertime','monthHoliday','breakMinutesActual','continuousDrivingMinutes','overtimeMinutes','rest','pendingBreak','availableAt','releaseAt','breakRun'])if(!Number.isInteger(c[key])||c[key]<0)fail('勤務整数');for(const x of c.dutySegments)if(!Number.isInteger(x.start)||!Number.isInteger(x.end)||x.start<Math.max(0,c.dutyStart)||x.end<=x.start||x.end>s.time||typeof x.work!=='boolean'||!['driving','standby','preparation','riding','break'].includes(x.kind)||(x.kind==='break')===x.work)fail('勤務区間');if(c.monthOvertime!==c.startLedger.month+Math.max(0,c.todayWork-480)+Math.max(0,c.weekDays.reduce((n,d)=>n+d.work,0)+c.todayWork-Math.max(0,c.todayWork-480)-2400)||c.yearOvertime-c.startLedger.year!==c.monthOvertime-c.startLedger.month)fail('超勤台帳');if(c.overtimeMinutes!==overtimeRecord(c).charged)fail('超勤実績区間');}for(const key of Object.keys(base.stats))if(!Number.isInteger(s.stats[key])||s.stats[key]<0)fail('評価整数');if(s.stats.overtime!==s.crews.reduce((n,c)=>n+c.overtimeMinutes,0))fail('超勤減点');if(s.important.some(n=>!Number.isInteger(n.time)||n.time>s.time||typeof n.msg!=='string'||typeof n.acknowledged!=='boolean'))fail('通知');const passengers=[...s.queues,...s.trains.flatMap(t=>t.passengers)];if(new Set(passengers.map(p=>p.id)).size!==passengers.length||passengers.some(p=>!Number.isInteger(p.dest)||p.dest<0||p.dest>7||!Number.isInteger(p.born)||p.born>s.time)||s.nextPassenger-1!==passengers.length+s.stats.transported)fail('旅客目的地保存');return s;}
export function restore(raw){if(typeof raw!=='string'||raw.length>3000000)throw Error('保存データ形式が不正です。');try{return validate(JSON.parse(raw));}catch(e){throw Error('読込拒否。現在のゲームは保持します。'+e.message);}}
